### ISSUE TITLE
Add `pkg.license.url` to package.json

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1001]
The banner is broken.

```
/*!
 * Fuel UX v3.5.1
 * Copyright 2012-2015 ExactTarget
 * Licensed under the BSD-3-Clause license ()
 */
```
See https://github.com/ExactTarget/fuelux-mctheme/blob/master/package.json#L19

**Comment by mbeard** [comment]
Looks like this has been resolved (see https://github.com/ExactTarget/fuelux/blob/master/package.json#L67).  Anything else that needs to be done?
