### ISSUE TITLE
Add option to hide or disable wizard step

### ISSUE THREAD

**Issue by cristalembalagens** [ExactTarget/fuelux#1013]
I would like to suggest to create an option in the wizard to block or hide some steps and make it jump over that step to the next or previous step. I think that hide would be better because it could reorganize the steps number and check for the last step easily.

**Comment by cormacmccarthy** [comment]
Can you provide some more detail please? What would the benefit be of hiding the steps instead of just removing them?

**Comment by cristalembalagens** [comment]
In some situations depending on what we choose in some steps we may need to hide or disable some steps ahead, but, if we go back and change that option those steps disabled may become enabled and another ones would be disabled, so we can't remove them because we may need them back.

**Comment by futuremint** [comment]
We have this same pattern in one of our applications, I think this is a valid feature we should add.

**Comment by scott-joe-williams** [comment]
Answered offline.

**Comment by cormacmccarthy** [comment]
Sounds great! We encourage you to contribute your idea as a PR and we can evaluate it. Thanks!
