### ISSUE TITLE
Deprecate checkbox and radio buttons

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux#1019]
We are deprecating `checkbox-custom` and `radio-custom`, in favor of simply using native controls.

This will be both easier to maintain into the future and has the added benefit of having behaviors that users (and developers) expect.

_Style_ the native controls to _look just like the custom controls did_ prior to deprecation, and add deprecation warnings to console similar to how the tree control does now. (rumor)

![custom-radio](https://cloud.githubusercontent.com/assets/362417/6003663/4a2f8022-aacb-11e4-9224-0195f345ed31.png)

![custom-checkbox](https://cloud.githubusercontent.com/assets/362417/6003668/5a982d24-aacb-11e4-9640-9e82b227cc57.png)

The custom controls will be removed in a future release.

**Comment by mbeard** [comment]
Add a style for an indeterminate state checkbox as well

**Comment by futuremint** [comment]
Example of setting the attribute: `$("#some-checkbox").prop("indeterminate", true);`.  This would be a "visual only" style on the checkbox and not effect the actual value of the input.

**Comment by futuremint** [comment]
We should still support highlight and toggling in some way... maybe with a smaller plugin.

**Comment by cormacmccarthy** [comment]
This actually isn't a breaking change because this can live alongside the old way.

**Comment by merong12** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

merongmall@naver.com 님께 보내신 메일 <Re: [fuelux] Deprecate checkbox and radio buttons (#1019)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
