### ISSUE TITLE
Improved namespacing of 'header' class name used in datepicker

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1030]
The datepicker markup uses a style called ‘header’. Change the name to ‘datapicker-wheels-header’ or something similar to namespace it to the datepicker control, so we can prevent style collisions. ‘header’ is a style we use elsewhere in our app and it’s a commonly used style name.

![screenshot 2015-02-03 08 38 14](https://cloud.githubusercontent.com/assets/347227/6044150/9818b55c-ac5f-11e4-9a47-4b5eceaec112.png)

**Comment by futuremint** [comment]
Closing this.  If we run into actual style collision problems we'll fix it later.
