### ISSUE TITLE
Make /dev/ a playground.

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux#1035]
I propose we:

* Remove `/dev/dev.html` from the Git repository, with --cache, so it doesn't get deleted.
* Move `/dev/dev.html` to `/dev/dev.html.example`.
* Add `/dev/dev.html.example` to the Git repository.
* Add `dev/*dev.html` to `.gitignore`.
* Add a `README.md` file to the `/dev/` directory with instructions for developers to duplicate `/dev/dev.html.example` as `/dev/dev.html` or `/dev/combobox.dev.html` or `/dev/snapdragons.dev.html` or whatever else seems appropriate. 

This would allow us to have a template that can be pulled from at any time, but not have the repo get littered up by people overwriting the dev stuff with each others changes.

**Comment by swilliamset** [comment]
:+1:

**Comment by cormacmccarthy** [comment]
pretty sure this is done except for the readme part. Will you update the readme please and close this issue @chriscorwin ?

**Comment by swilliamset** [comment]
Lets include a suggestion in the README to use jsbin or whatever to share your sandbox on PR's (when necessary).

Granted a solid unit test should prevent the need for the jsbin but in some instances the jsbin would be value (philosophies as to when and why and whatever should be outside the scope of this issue).

**Comment by swilliamset** [comment]
fixed by https://github.com/ExactTarget/fuelux/pull/1068
