### ISSUE TITLE
Highlight form building HTML tab

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1040]
I didn't see the HTML tab at first glance. Could we highlight it by changing the color of the text, etc. @cmcculloh ?

![screen shot 2015-02-05 at 4 35 11 pm](https://cloud.githubusercontent.com/assets/1290832/6069748/f8fb5a5a-ad54-11e4-8f09-87a29b7aedb2.png)

**Comment by cormacmccarthy** [comment]
:+1: Sure thing!
