### ISSUE TITLE
Spinbox needs a background color

### ISSUE THREAD

**Issue by jmgekeler** [ExactTarget/fuelux#1042]
The spinbox needs a white background so it doesn't look disabled when over different colors.

![fuel_ux_snippets](https://cloud.githubusercontent.com/assets/450099/6080466/afe9c7a8-addf-11e4-9414-1ffbea57b8f9.png)

**Comment by cormacmccarthy** [comment]
Bootstrap provides this already for form controls: https://github.com/twbs/bootstrap/blob/master/less/forms.less#L123

![image](https://cloud.githubusercontent.com/assets/8006971/6085373/254841b0-ae07-11e4-8cff-96a9b1f62efc.png)

Can you provide a jsfiddle or something of your code so we can debug further? Thanks.

**Comment by mbeard** [comment]
I think this is mctheme related, not fuelux.

**Comment by jmgekeler** [comment]
Yes, it's an issue with mctheme. My mistake.
