### ISSUE TITLE
Typo: repeater-viewpor

### ISSUE THREAD

**Issue by TheJaredWilcurt** [ExactTarget/fuelux#1043]
>The three sections of a repeater are repeater-header, **repeater-viewpor**, and repeater-footer. Custom controls can be placed in repeater-header if needed. To simplify this tutorial, header controls have been disabled.

* http://fuelux-tutorials.herokuapp.com/repeater/#markup

**Comment by interactivellama** [comment]
Thanks @TheJaredWilcurt. Fixed.
