### ISSUE TITLE
check in checkbox is not placed optimally

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1050]
![image](https://cloud.githubusercontent.com/assets/8006971/6088227/44b7c71c-ae22-11e4-9f72-b1a65706e988.png)

I think this looks better:
![image](https://cloud.githubusercontent.com/assets/8006971/6088261/78307d3c-ae22-11e4-9b8c-15bcb64505cc.png)

    .checkbox-custom:before{
        padding: 1px 0 0 2px;
    }

does the trick.

Here are the two side by side (current way on left, proposed way on right):
![image](https://cloud.githubusercontent.com/assets/8006971/6088280/bdafaf0e-ae22-11e4-9b9a-296c2d327990.png)![image](https://cloud.githubusercontent.com/assets/8006971/6088288/cdbfd608-ae22-11e4-859c-edacbb837c66.png)

**Comment by shaneparsons** [comment]
The above makes the checkbox offset to the right in `.input-group-addon` and any `checkbox-inline input[checked="checked"]`.

Here's a fix for the `.input-group-addon`(kind of hacky):
```
.fuelux .input-group-addon.checkbox-custom.checkbox-inline:before{
   padding: 1px 0 0 1px;
}
```
Couldn't figure out how to fix `checkbox-inline input[checked="checked"]`.

**Comment by shaneparsons** [comment]
What's interesting is how if you zoom into the page, all checkmarks are good and don't need any adjusting from the original source code at all.

**Comment by swilliamset** [comment]
@shaneparsons thank you for your feedback. if this is still an issue PRs are welcome.
