### ISSUE TITLE
'for' attribute in radio label completely breaks functionality of radio group

### ISSUE THREAD

**Issue by scott-joe-williams** [ExactTarget/fuelux#1055]
http://jsbin.com/medije/2/edit

I used the Fuel UX form builder to build a form and it included the `for` attribute on the label for a radio button in accordance of the W3C standards:
> When a LABEL element receives focus, it passes the focus on to its associated control.

http://www.w3.org/TR/html4/interact/forms.html#h-17.9.1

**Comment by interactivellama** [comment]
This works: http://jsbin.com/tujokesonu/1/edit

I think there was some circular focusing going on. Both `ID` and `FOR` were on the label.

**Comment by swilliamset** [comment]
http://jsbin.com/kufutiwedo/1/edit (corrected version of http://jsbin.com/medije/2/edit)

@scott-joe-williams `id` is on the `label` and should be on the `input` in your example. once the `id` is moved it works. was the markup in the example a result of the form builder? if so it needs to be corrected.

as for fuelux radio buttons what is the preferred markup? with or without `for`? we do support both. should we? should we encourage good markup?

**Comment by swilliamset** [comment]
Confirmed problem is with form builder

https://github.com/ExactTarget/fuelux/issues/1056

**Comment by cormacmccarthy** [comment]
ID needs to be left on the label, because the input element is sr-only. I don't remember _exactly why_ id needs to be left on the label, but, I do have a gut feeling about this and the id needing to be on the label and not the input or _something_ breaks. I think that if we do anything here, it should be to remove the "for" _not_ the move the id.

**Comment by cormacmccarthy** [comment]
Sorry, moving conversation to here: #1057

**Comment by cormacmccarthy** [comment]
Thanks for the find @scott-joe-williams
