### ISSUE TITLE
form builder adds `id` to `label` instead of `input` for radio buttons

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1056]
https://github.com/ExactTarget/fuelux/blob/gh-pages/assets/js/form-builder/templates/component/multipleradiosinline.html#L6

![screen shot 2015-02-09 at 11 21 58 am](https://cloud.githubusercontent.com/assets/347227/6110152/eb8270ce-b04d-11e4-88a7-a63e48b3c77f.png)

**Comment by interactivellama** [comment]
Thanks. Just about to do that.
