### ISSUE TITLE
Fork Me banner invisibly blocks HTML output button on Form Builder

### ISSUE THREAD

**Issue by scott-joe** [ExactTarget/fuelux#1067]
![screen shot 2015-02-09 at 10 42 37 pm](https://cloud.githubusercontent.com/assets/2026866/6121261/83271286-b0ad-11e4-9211-a14398f0d8a0.png)

After creating the same form **4** times, I realized why the output button was redirecting me to the github page only sometimes :rage4:

**Comment by interactivellama** [comment]
Yeah, it doesn't seem to be a problem that that Internet has solved. The only thing I can think of is 3 images in a table!
