### ISSUE TITLE
Release automation stuff

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1070]
All this needs to be _one step_:

1. `git checkout master && git pull origin master`

1. `git checkout 3.x && git pull origin:3.x`

1. `git merge master`

1. `grunt release` or `grunt release --minor`
      * Updates the `package.json` and `bower.json` using semver. This will build the `dist` folder and update version numbers within markdown files. Visually check that `dist` file banners have the new version and commit. You will need `SAUCE_API_KEY.yml`.

1. `git add dist && git add *.md && git add *.json && git commit -m 'release x.x.x'`

1. Upload contents of `dist` folder to Fuel CDN server via FTP.

1. Push to `origin:3.x`.

1. Create tag locally. `git tag -a x.x.x -m 'vx.x.x'`. Publish tag to Github: `git push origin x.x.x`. The tag commit should exist in the major.x branch.

**Comment by cormacmccarthy** [comment]
Also, some steps are missing here. Prior to step 4 you must:

1. Update version in package.json:81
1. Update version in bower.json:4

**Comment by interactivellama** [comment]
Version is updated in Step 4. See grunt-bump task inside `grunt release` 
https://github.com/ExactTarget/fuelux/blob/master/Gruntfile.js#L423

**Comment by interactivellama** [comment]
I do not recommend auto uploading files to Fuel CDN or pushing tags to origin as part of a grunt task. 1-5 could easily be one task if everything merged correctly. There's always the possibility of extra commits in the release branch though.
