### ISSUE TITLE
Repeater: list_rowRendered issue

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux#1075]
The helpers object that is passed into custom row renderer function has changed with #1022 .

Previously, `helpers.rowData` was an object that represented the current row.  Now it is an array that represents *all* rows.

Previously:
![screenshot 2015-02-10 18 28 14](https://cloud.githubusercontent.com/assets/467352/6138823/b9a93dca-b152-11e4-8c1c-a6dcac3c866e.png)

Currently:
![screenshot 2015-02-10 18 28 39](https://cloud.githubusercontent.com/assets/467352/6138827/be4bb042-b152-11e4-9079-0596934b63b5.png)

**Comment by futuremint** [comment]
Which callback are you using?  The poorly named `list_columnRendered` has the correct code and is operating correctly in an application I'm using with the latest from master.  It uses [this code](https://github.com/ExactTarget/fuelux/blob/master/js/repeater-list.js#L251:L254) to create `rowData`.  It sounds like you are using the `list_rowRendered` callback which uses [this code](https://github.com/ExactTarget/fuelux/blob/master/js/repeater-list.js#L380:L382) which would give you a `rowData` like you are seeing.  This is correct per the current documentation, and this behavior doesn't change with the new repeater.js updates.

For comparison, here is the code from our prior release in that list extension that does the same thing.  You will see it creates `rowData` the same way.  [Here is theold  `list_rowRendered` call](https://github.com/ExactTarget/fuelux/blob/3.5.1/js/repeater-list.js#L395:L408) and [here is the old `list_columnRendered` call](https://github.com/ExactTarget/fuelux/blob/3.5.1/js/repeater-list.js#L453:L467).
