### ISSUE TITLE
.scheduler() Initialization function is not working on click event of an Anchor or button.

### ISSUE THREAD

**Issue by samfreelancer** [ExactTarget/fuelux#1076]
I am calling initialization function on click event of an anchor.
$(document).ready(function(){
$('.call-scheduler').on('click', function(){
$('.scheduler').scheduler();
});
});
Error i get once the click event is raised: TypeError: $(...).scheduler is not a function

However to diagnose this issue i call the initialization function inside document ready itself and it worked fine. I think intialization is not working on click event of the anchor or button.Can anybody help me on this. I have included the dependencies mentioned below.
<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="/css/twitter-bootstrap.3/bootstrap.custom.css" />
	<link rel="stylesheet" type="text/css" href="/css/twitter-bootstrap.3/bootstrap.switch.css" />
	<link rel="stylesheet" type="text/css" href="//www.fuelcdn.com/fuelux/3.5.0/css/fuelux.css" />

	<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.js"></script>
	<script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.js"></script>
	<script type="text/javascript" src="//cdn.jsdelivr.net/handlebarsjs/1.3.0/handlebars.js"></script>
	<script type="text/javascript" src="//www.fuelcdn.com/fuelux/3.5.0/js/fuelux.js"></script>

**Comment by mbeard** [comment]
Here's a working [example](http://jsbin.com/hofadamegu) that illustrates initialization on click of a button.  Does this work for you?  If not, could you provide a complete example of your code.
