### ISSUE TITLE
Datepicker: type colors and border radius inconsistent with rest of Fuel UX

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1088]
Type colours are mysteriously being overridden, rather than inheriting bootstrap defaults.

Border radius on the buttons is also being overridden to be 0 instead of the default 4px.

**Comment by chriscorwin** [comment]
I don't understand what is being asked for here. 

Which colours should be using `@gray13`?  

What is being overridden? Where is it being overridden? 


Also note: `@gray13` is not a variable in Fuel UX, only in the Marketing Cloud Theme.
