### ISSUE TITLE
Update dist and qunit process

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1094]
QUnit should run on the compiled dist code, which should be generated when QUnit task is kicked off.

Everyone should be checking in their dist --OR maybe not(!).

* Update Grunt tasks to make qunit task generate the dist and then run qunit
* Update QUnit to test the dist files instead of the dev files
* ~~Update documentation to tell people to always commit their dist files~~
* ~~Update documentation to tell people how to deal with the now more frequent merge conflicts that this will result in~~

Maybe also keep the current way to run unit tests around so you can test your files while you develop on them for speed. Like a qunit-dev task or something, idk...

**Comment by interactivellama** [comment]
I don't think we should have dist files in Pull Requests, so we would need a way to delete them at the end of the unit tests, too.

If we truly need to test the fuelux.js and fuelux.min.js, it should be a part of the release task and probably be a URL variable set in `test/fuelux.html`that conditionally loads the dist JS instead of the individual controls.

**Comment by swilliamset** [comment]
Dist should not be committed on every PR

**Comment by cormacmccarthy** [comment]
OK, closed the pull request because I've been thinking about the `dist` directory stuff and trying to make sure we are making the change intelligently. The problems as I saw them were:
1) People weren't actually testing their changes (which included making sure it would compile to dist and testing dist, which means testing everything together whereas previously we were only testing everything separate, as separate modules)
2) `dist` was often completely out of date

One way to "fix" this is just have everyone compile and check in dist. However, there are some specific problems with this:
A) Muddies the PRs (there are strategies to get around this, but, we are still "getting around" it)
B) (and this is the key one for me) It complicates automation. If we want to do automated merges of more than just one branch and master, we have to do extra work to compensate for the merge conflicts
C) It complicates merges. If you branched off of an older version of master and then you want to merge in the newer version of master, you'll have very easily fixable (but annoying) merge conflicts (edited)


I'm going to be thinking about this over the weekend, and hope to get a chance to look at the links that the Stephens provided, but, I just wanted to let you know why I killed the PR and that I don't consider the topic "closed" in my mind and may actually end up arguing for keeping it the way we have it. I think we can solve the stated problems in different ways than the "obvious" way of having everyone commit their dists

**Comment by swilliamset** [comment]
http://githooks.com/

Another approach to consider (as if we don't have enough) is a git hook on post commit. This could keep the build step separate from development work but reinforce the dist folder staying up-to-date.

**Comment by cormacmccarthy** [comment]
For now, address `dist` dir confusion with a pre-commit (or pre-pr???) hook that blocks PRs with `dist` changes from being submitted so the user knows immediately. #1104

**Comment by swilliamset** [comment]
Abandoned

**Comment by cormacmccarthy** [comment]
To provide a bit more clarity, a lot of work was done around this, but, no _more_ work will be done for this particular issue (any more work around this topic will be done under a new issue. This one is now closed).
