### ISSUE TITLE
Document that edge server should be run in dev mode

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1095]
Should we document this? I even forget about it today deploying a YAHA (yet another heroku app) for the mctheme styleguide sync. Otherwise grunt doesn't get installed so no dist built. Maybe in details.md?

```
heroku config:set npm_config_production=false
```

**Comment by cormacmccarthy** [comment]
sounds like a good idea to me...

**Comment by swilliamset** [comment]
documented [here]( https://github.com/ExactTarget/fuelux/blob/61b991d83f08525fe568fb3e027cef147dfc6140/DETAILS.md#edge-servers)
