### ISSUE TITLE
Implement `npm start` task in package.json

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1097]
This task should start what needs to be viewed (probably using grunt) and probably run unit test before the connect server runs. Could be `grunt serve` without `watch` task.

There is a question whether `dist` should be built (specifically the CSS).

**The main task is to align Elements and Fuel UX**, so there are no "which task am I supposed to use? Oh right, it's `buildjs` in Elements and `distjs` in Fuel."

- [x] point `npm start` to most intelligent/applicable grunt task to start server. Probably `grunt serve`
- [x] make sure `npm install` runs appropriate things (such as `bower install`)

**Comment by cormacmccarthy** [comment]
:+1: 

This could easily be folded under #1094

**Comment by cormacmccarthy** [comment]
point `npm start` to `grunt serve-fast`

**Comment by swilliamset** [comment]
do it
