### ISSUE TITLE
Fuel UX Tree - Make unselected data available in some form

### ISSUE THREAD

**Issue by AdiPandit** [ExactTarget/fuelux#1101]
When a node is unselected the data for the unselected element is not available via the unselect event. 
This makes it difficult to handle the unselect event in the UI. 

Code snippet from fuelux.tree.js
```javascript
  if($el.hasClass('tree-selected')) {
				eventType = 'unselected';
				...other unselect logic
			} else {
				//.. select logic .... makes the data available
				if (this.options.multiSelect) {
					data.push( $el.data() );
				}
			}
```
Would it be feasible to provide this data via some structure like unselectedItem or lastUnselectedItem?

**Comment by swilliamset** [comment]
Great catch!

We'll put this on the queue. Any use cases and/or PR's you can provide would certainly be appreciated.

**Comment by mbeard** [comment]
The data-attributes on the element should be available as demonstrated (here)[http://jsbin.com/halujoyinu].

```
$('#myTree').on('deselected.fu.tree', function(evt, data) {
    console.log('deselected', data.selected[0].dataAttributes);
});
```

**Comment by AdiPandit** [comment]
Thanks for the responses.

Matt,
I tried hooking into the "unselected" event but for some reason I do not
see it getting fired. "update" event gets fired for both actions
select/unselect via click.
Tried binding to unselected, deselected,deselected.fu.tree with no effect.

-adi

**Comment by mbeard** [comment]
Can you verify the version of Fuel UX you are using - is it the latest?  The `deselected` event was added to tree with version 3.1.0. so just want to confirm.  Were you seeing the attributes logged to the console in the JS Bin example?  Could you provide a complete snippet that shows this issue so we can troubleshoot.

**Comment by AdiPandit** [comment]
Looks like I have an older version. I couldn't check the version as the
code is the one which came bundled with ace and does not mention the
version.
One of my colleagues was able to find a workaround which should work fine
until we can upgrade to a newer fuelux version.
Thank you for your prompt responses.

This issue can be closed.

-adi

**Comment by mbeard** [comment]
Thanks for confirming @AdiPandit.  Let us know if you run into anything else in the future.

**Comment by swilliamset** [comment]
@AdiPandit curious what is this "ace" you speak of? Also any additional information you can provide about how your team is using fuelux would be greatly appreciated. We are always looking for more user stories.

**Comment by interactivellama** [comment]
I think @AdiPandit means [Ace Admin](http://responsiweb.com/themes/preview/ace/1.3.3/). Although I'm not 100% sure that it uses Fuel UX 3. Older versions did, because we have had questions about Bootstrap 2 and Fuel UX 2 before.

**Comment by interactivellama** [comment]
I spoke too soon. I'm guessing Ace Admin is using an old version. Not sure of the version, but here is the code. http://responsiweb.com/themes/preview/ace/1.3.3/dist/js/fuelux/fuelux.tree.min.js

Does it break our license to remove the banner that says it's Fuel UX? It actually looks like it's mangled to be compressed.
