### ISSUE TITLE
Lightweight validation control?

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1129]
- Lightweight validation control for inputs (use of popover?)
- Write wiki for using a third-party validation plugin

**Comment by cormacmccarthy** [comment]
When you say "validation" control, you don't mean "it does the validation" correct? This is more of an alert or notification control that you are able to supply to any arbitrary form elements, right?

**Comment by interactivellama** [comment]
Use [Bootstrap tooltip control](http://getbootstrap.com/javascript/#tooltips) for the time being.

**Comment by swilliamset** [comment]
mctheme provides styling of tooltip to match pattern library https://github.com/ExactTarget/fuelux-mctheme/issues/174
