### ISSUE TITLE
tree select bug

### ISSUE THREAD

**Issue by ktmswzw** [ExactTarget/fuelux#1137]
when 
$.fn.tree.defaults

multiSelect:false,folderSelect:true

lost folder style

#3139
$all.removeClass( 'tree-selected' ).find( '.glyphicon' ).removeClass( 'glyphicon-ok' ).addClass( 'fueluxicon-bullet' );

change to

$all.removeClass( 'tree-selected' ).find( '.glyphicon' ).removeClass( 'glyphicon-ok' );
$all.find( '.icon-item' ).addClass( 'fueluxicon-bullet' );

**Comment by interactivellama** [comment]
Thanks, @ktmswzw.

**Comment by interactivellama** [comment]
@ktmswzw that did not solve it for me. I'm working on a refactor the tree select methods, and I think I solved this. Will PR in the next week.
