### ISSUE TITLE
Set phantomjs timeout higher?

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1138]
In several instances I've had phantomjs timeout on a unit test that was taking too long to execute (and thus, I've had to modify the unit test to support phantomjs's limitations) and now periodically it will timeout while doing the blanket task and kill the default `grunt` process. Is there a way to set phantomjs's timeout higher to help alleviate this?

**Comment by swilliamset** [comment]
@cormacmccarthy After 3.6.4 release update status of timeout regularity

**Comment by mbeard** [comment]
You can set a `resourceTimeout` option [like so](http://phantomjs.org/api/webpage/property/settings.html)

**Comment by cormacmccarthy** [comment]
![image](https://cloud.githubusercontent.com/assets/8006971/6925996/62d4b1e8-d7b1-11e4-8e5e-49c93fcfe78a.png)
