### ISSUE TITLE
Clean up tree methods

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1148]
There is a `render` and a `populate` method that are public but should be private. Calling them is almost never a good idea. Render is merely a shortcut for populate, except that it passes itself into populate. Populate will literally populate _any passed in element_ that is a valid tree element, regardless of whether it is already populated, without emptying it first.

- [ ] make `render()` be instead a "refresh" that will empty the tree and then populate it from the datasource.
- [ ] privatize the `populate()` method

**Comment by interactivellama** [comment]
We may want to transition out of the object literal structure.

**Comment by interactivellama** [comment]
See #1302. Closing. Privatizing the `populate()` method should be part of a larger privatization project.
