### ISSUE TITLE
support for item property crawling for columns (nested object items) of repeater

### ISSUE THREAD

**Issue by Daskul** [ExactTarget/fuelux#1149]
tried searching if its possible to access the property of item if its an object.

var columns = [
        {
            label: 'Inquiry No.',
            property: 'id',
            sortable: true
        },
        {
            label: 'Inquirer',
            property: 'inquirer.name',
            sortable: true
        }
    ];

Like here `inquirer.name`

**Comment by interactivellama** [comment]
The quick answer is not right now. Right now, it's expected that the columns array be "flat." a custom datasource can reduce your array and generate a "flat array" to send into columns from inside the datasource function.

A custom dataSource is your playland to manipulate the data into a reduced array. 

The dataSource part of the [repeater tutorial](http://fuelux-tutorials.herokuapp.com/repeater/#static) may be helpful. Manipulate the default data that gets returned in the callback.

```
// define the datasource
  var dataSource = {
    'page': pageIndex,
    'pages': totalPages,
    'count': totalItems,
    'start': startIndex,
    'end': endIndex,
    'columns': columns, // <--- this needs to be "flat"
    'items': rows // <-- can be any data you want that corresponds to your columns property, but it's also expected to be "flat"
  };

  // pass the datasource back to the repeater
  callback(dataSource);
```

**Comment by Daskul** [comment]
got it! thank you. keep it up guys!
