### ISSUE TITLE
Clean up repeater example.js

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1150]
It is hard to read and hard to comprehend. Variables are named poorly as if uglified, even though the file is just a normal js file. This file, since it is supposed to be helping our users understand a complex concept ("repeater") should be as clear as possible.

Here's a good example of what I'm targeting here (lines 85-89):

		i = options.pageIndex * (options.pageSize || 50);
		l = i + (options.pageSize || 50);
		l = (l <= resp.count) ? l : resp.count;
		resp.start = i + 1;
		resp.end = l;

https://github.com/ExactTarget/fuelux/blob/gh-pages/assets/js/repeater-examples.js

**Comment by interactivellama** [comment]
Can I add the task "add .fu-callout .fu-callout-warning" div mentioning 
- view extensions 
- their file names 
- that they are necessary or repeater won't work.
- Add a link to [repeater tutorial](http://fuelux-tutorials.herokuapp.com/repeater/)

**Comment by interactivellama** [comment]
From #1149.

The quick answer is not right now. Right now, it's expected that the columns array be "flat." a custom datasource can reduce your array and generate a "flat array" to send into columns from inside the datasource function.

A custom dataSource is your playland to manipulate the data into a reduced array. 

The dataSource part of the [repeater tutorial](http://fuelux-tutorials.herokuapp.com/repeater/#static) may be helpful. Manipulate the default data that gets returned in the callback.

```
// define the datasource
  var dataSource = {
    'page': pageIndex,
    'pages': totalPages,
    'count': totalItems,
    'start': startIndex,
    'end': endIndex,
    'columns': columns, // <--- this needs to be "flat"
    'items': rows // <-- can be any data you want that corresponds to your columns property, but it's also expected to be "flat"
  };

  // pass the datasource back to the repeater
  callback(dataSource);
```

**Comment by cormacmccarthy** [comment]
Documentation cleanup coming in #1152, those are good key points to make sure get in with that change. Thanks!
