### ISSUE TITLE
Use templating for example markup

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1154]
At the very least take advantage of `require` and `_.template()` to pull in markup from the `/markup` folder into examples etcetera, so we don't have to update boilerplate code all over the place anytime we change anything.
- [ ] Bring Underscore Form Builder templates into Fuel UX proper
- [ ] Bring Handlebars Fuel Site templates into Fuel UX proper
- [ ] Make sure there is parity between the Underscore and Handlebars templates
- [ ] Eliminate every instance of markup in this repository (both `master` and `gh-pages`) and replace with usage of templates
- [ ] Create tickets on, at minimum, the Fuel UX site repo to utilize templates served from Fuel UX dist

Here is a possibly non-complete list of the internal UXA/Fuel UX properties that could benefit from this:
- [form builder](https://github.com/ExactTarget/fuelux/tree/gh-pages/assets/js/form-builder/templates/component)
- [snippets](https://github.exacttarget.com/uxarchitecture/fuelux-snippets)
- pages
- [tutorials](https://github.exacttarget.com/uxarchitecture/fuelux-tutorials)
- fuel UX site
- [getfuelux docs](http://www.getfuelux.com)
- marketing cloud theme example pages
- components
- page templates

**Comment by swilliamset** [comment]
:+1:  can we create a check list of what examples are NOT doing this?

**Comment by mbeard** [comment]
I think this would be valuable for the controls themselves.  Essentially having an option that could initialize the control with markup so that the developer just needed a container element.  Would be especially helpful for our controls with substancial markup - like repeater and scheduler.

**Comment by swilliamset** [comment]
+:100:

**Comment by interactivellama** [comment]
:+1: I would propose a server side include solution, so that the HTML can be viewed without JS running (possibly with some connect middleware?), since we are modify the markup with our JS controls. We currently have 2 markup folders, and index.html to update, we got halfway there with require-text'ing the unit test markup, but should proceed farther.

**Comment by interactivellama** [comment]
How about this one? https://github.com/soenkekluth/connect-ssi 

It mimicks the old server side include.

**Comment by cormacmccarthy** [comment]
Form builder now has several bootstrap and fuelux controls templatized as Underscore templates. The fuelux-site has the specifically Fuel UX controls templatized as Handlebars templates. Would be great to get both of those templates moved over into the dist folder of the Fuel UX repo and have all projects use those templates as served by Fuel UX (including the test examples in the Fuel UX project itself).
