### ISSUE TITLE
release notes for 3.6.4

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1163]

**Comment by cormacmccarthy** [comment]
## Feature and bug fix release

### New Features and enhancements
#1141 Added data-name for selectedItem [wizard]
#1115 adds deprecation notice about checkbox and radio buttons to getfuelux.com [checkbox][radio][documentation]

###  Bug Fixes
#1173 Datepicker goofy Chrome character fix [datepicker]

### Plumbing
#1177 Adds comment about phantomJS timeouts
#1144 Add IDs to html sections of index.html [documentation]
#1136 Update package.json with latest dependencies 


### Upgrade Notes
Checkbox and Radio controls are now deprecated and will be removed in the future (probably in 3.7.0) in favor of simple markup styling with no JS component. Markup recommendations for checkbox and radio are forthcoming.
