### ISSUE TITLE
fuellux install issue

### ISSUE THREAD

**Issue by khandah** [ExactTarget/fuelux#1170]
![07-03-2015 3-23-30 pm](https://cloud.githubusercontent.com/assets/11368276/6543143/98210922-c4de-11e4-825b-7e5e2352516c.gif)
I followed the install process step by step.
But at the end I got some issues. Please see attached screen capture.
Thank you in advance.

**Comment by interactivellama** [comment]
Did you bower install or git clone? If `bower install` was used, not all files that are needed to view `index.html` may be present. `index.html` is used primarily for development purposes.

Are there any missing files in the console?
