### ISSUE TITLE
Pagination for the last page is displaying incorrect #

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1174]
Pagination for the last page is displaying incorrect #, if there are only 298 automation, it displays 250-300 of 298.

![image](https://cloud.githubusercontent.com/assets/157303/6645874/4c322fa2-c996-11e4-9dfd-dc9755ce45d2.png)

**Comment by cormacmccarthy** [comment]
Still trying to replicate. This may not be a Fuel UX bug...

![image](https://cloud.githubusercontent.com/assets/8006971/6646013/504ac03a-c997-11e4-8059-fc2c8088db54.png)

**Comment by mbeard** [comment]
Here is an example with similar row count.  It doesn't seem to be in the repeater at first glance.
http://jsbin.com/rupuvasiwa

**Comment by cormacmccarthy** [comment]
Thanks Matt! :)

**Comment by cormacmccarthy** [comment]
![image](https://cloud.githubusercontent.com/assets/8006971/6646431/2961841e-c99b-11e4-9087-ffb713d784a7.png)

Confirmed that they are running 3.6.3

**Comment by mbeard** [comment]
I tried with that row count and page size and still don't see an issue.  What does the logic with their data source provider look like?  I imagine that the REST API they are calling should be giving back the `total` row count and they should be looking at the options passed into the data source function to find the item range.  Should resemble something like this:

```
$.ajax({
  type: 'post',
  url: '/repeater/data',
  data: options
})
.done(function(data) {

  var items = data.items;
  var totalItems = data.total;
  var totalPages = Math.ceil(totalItems / pageSize);
  var startIndex = (pageIndex * pageSize) + 1;
  var endIndex = (startIndex + pageSize) - 1;

  if(endIndex > items.length) {
    endIndex = items.length;
  }

  // configure datasource
  var dataSource = {
    page: pageIndex,
    pages: totalPages,
    count: totalItems,
    start: startIndex,
    end: endIndex,
    columns: columns,
    items: items
  };

  // invoke callback to render repeater
  callback(dataSource);
});
```

**Comment by cormacmccarthy** [comment]
Yeah, _just discovered_ that their dataSource was, for some reason, passing the incorrect data back. This is not a Fuel UX bug.

Thanks for the help!
