### ISSUE TITLE
support `disabled` and `checked` attributes minus `=disabled` and `=checked`

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1179]

**Comment by swilliamset** [comment]
Initially identified with native (no js) implementation of checkbox and radio button because of using sudo selectors in less. Could be a good place for a mixin.

**Comment by mbeard** [comment]
In other words, these two examples should have equivalent styling and behavior.
`<input type="checkbox" checked="checked" disabled="disabled" />` and
`<input type="checkbox" checked disabled />`

**Comment by interactivellama** [comment]
Fixed by #1220.
