### ISSUE TITLE
Scheduler with end date displays wrong start date!

### ISSUE THREAD

**Issue by biolau** [ExactTarget/fuelux#1183]
1 - I created a test page using the "No AMD/UMD Template" from the getting started section.
2 - I added the example for the scheduler

When the page is displayed the start date becomes "09/19/2014" even so the scheduler is created with '2014-03-31T03:23+02:00'.

If I remove the UNTIL from the rule it displays '03/31/2014' which is what is expected.

**Comment by interactivellama** [comment]
It looks like this had something to do with `dateClicked` not firing from datepicker. It should be fixed in v3.8.0.
Scheduler w/ 3.7.3 http://codepen.io/interactivellama/pen/yNPbgb
Scheduler w/ 3.8.0 http://codepen.io/interactivellama/pen/mJqmyg
