### ISSUE TITLE
Rename mixin parameters to match Bootstrap dash-case-style.

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux#1186]
It recently came to light in Issue #1158 that the gradient mixin is using named parameters that are in "camelCase" rather than "dash-case" style.

Do we have a recommendation about such names?

I submit that such names ought be "dash-case", and a refactoring is in order.

See: [coding standards](http://programmers.stackexchange.com/questions/186407/why-bootstrap-3-changes-camelcase-to-dashes-is-it-more-readable) question at StackExchange.

**Comment by swilliamset** [comment]
table until after 3.6.5

**Comment by swilliamset** [comment]
Please provide a list of changes so we understand the scope.
