### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by scott-joe-williams** [ExactTarget/fuelux#1187]
At the bottom of the readme
![screen shot 2015-03-23 at 4 33 37 pm](https://cloud.githubusercontent.com/assets/2026866/6789932/5eb2fe7c-d17a-11e4-8eaa-f2f1314eef18.png)

**Comment by Alondite00** [comment]
Is this supposed to go somewhere?  If not I'll take it out.

**Comment by scott-joe-williams** [comment]
I'm assuming it's supposed to go to gitanalytics...You should try and see who put it there. it may be some sort of performance notification

**Comment by Alondite00** [comment]
@interactivellama Is this link alright to remove? The analytics creators seem to be missing, and this goes to a japanese site.

**Comment by interactivellama** [comment]
It's been there a long long time. Yes, please PR removal: https://github.com/ExactTarget/fuelux/commit/a6ae9095e29cd2b69be2b2b9e075b0aa1e8985e6
