### ISSUE TITLE
Add better dropdown pagination for repeater

### ISSUE THREAD

**Issue by kevinparkerson** [ExactTarget/fuelux#1198]
@jschmidtatet had a good idea on maintaining the combobox pagination for a high number of pages. Essentially, it would take the current page, and only show n pages before and after the current page in the combobox. For example, on page 1, the combobox would show pages 1-20, on page 220, the combobox would show 210-230, on the last page (300), the combobox would show 280-300.

NOTE: this needs to be discussed with design prior to any work being started

**Comment by jschmidtatet** [comment]
The implementation in jbinteractions shows the first N pages, the N pages preceding the current page, the N pages following the current page, and the last N pages. That way a customer with 100,000 pages of results has some convenient page navigation around the beginning of the list, their current page, and the end of the list. Here's pseudo-code based on what we have in jbinteractions:

    // Prerequisites:
    //      totalPages
    //      currentPage
    //      maxPageSeries
    //      pageHTML

    var pageAdded; // Scoped outside function, could be written differently
    function addPage( i ) {
        // Skip page numbers already shown. Prevents duplicates.
        if( pageAdded[ i ] ) {
            return;
        }

        // Add page to list
        pageHTML += '<li><a>' + i + '</a></li>';

        // Mark page as added
        pageAdded[ i ] = true;
    }

    // Each for loop is bounded by a lowest page number of 1 and a top page
    // number of totalPages, preventing any strange out-of-bounds numbers. The
    // use of the addPage() method which has early-exit for seen page numbers
    // prevents duplicate page numbers from appearing.
    //
    // In the situation where...
    //      totalPages === 100
    //      currentPage === 50
    //      maxPageSeries === 3
    //
    // The resultant list of pages would be:
    //      1, 2, 3, 47, 48, 49, 50, 51, 52, 53, 98, 99, 100
    //
    // This gives the user the ability to navigate near the current page, jump
    // to pages near the beginning, and jump to pages near the end. For all
    // other page numbers, they can use the drop-down. In production
    // environments, I would suggest a higher maxPageSeries, such as 10 or 50.
    // Kept small here for demonstration.

    pageAdded = {}; // Reset seen list
    for( i = 1 ; i <= totalPages && i <= maxPageSeries ; ++ i ) {
        addPage( i );
    }
    for( i = Math.min( 1 , currentPage - maxPageSeries ) ; i <= totalPages && i <= currentPage + maxPageSeries ; ++ i ) {
        addPage( i );
    }
    for( i = Math.min( 1 , totalPages - maxPageSeries ) ; i <= totalPages ; ++ i ) {
        addPage( i );
    }

**Comment by kevinparkerson** [comment]
Discussed this with Jamin, and the dropPagingCap / secondary paging configuration currently available is the desired pattern across all applications. We won't be implementing this feature, and instead will be converting JB to that style when upgrading to Fuel UX 3
