### ISSUE TITLE
Repeater controls not disabling during data load

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1212]
When you change pagination view on repeater and the ajax call is executing, you are able to still paginate and sort via dropdown and search.

When you interact with a filter, all filters should disable until interaction resolves.

Here is the original issue in MCAS that is generating this ORCA request:

> qa keeps coming back with issues relating to repeater controls being clickable while dataSources are loading and seeing repeated data. Is this something that should be the app's responsibility to handle?  I've already implemented this in a few spots, but there are a lot of edge cases with all of our filtering/sorting/etc. Could the fuel controls just disable all buttons on its control while the datasource is loading or ensure that the container is empty before appending the datasource response?

**Comment by interactivellama** [comment]
I'd propose a 'loading' state that disables any interactions and fires an event at the end. Although we already have a `loaded.fu.repeater`event and might be confusing.

Other options might be `ready.fu.repeater` as in I'm ready now to interact with the user (like jQuery DOM). @cmcculloh any thoughts?

**Comment by cormacmccarthy** [comment]
`disabled.fu.repeater` could maybe do the trick.
`ready.fu.repeater` or `enabled.fu.repeater` or even just recommend the utilization of `loaded.fu.repeater`?

**Comment by cormacmccarthy** [comment]
Easiest way to reproduce this is to go [here](http://fuelux-snippets.herokuapp.com/repeater-advanced) and click "grid" and then immediately "paragraph" view. You'll get this:

![image](https://cloud.githubusercontent.com/assets/8006971/7047881/70d1e068-dddd-11e4-9851-a974701bb2f9.png)
