### ISSUE TITLE
Error when deselected row in repeater

### ISSUE THREAD

**Issue by rookawa** [ExactTarget/fuelux#1213]
when setup repeater with 'list_selectable' as below

```javascript
list_selectable: 'single', // happen on both 'single' and 'multi'
```

and try selected and deselected row, console will show

Uncaught TypeError: Cannot read property 'trigger' of undefined

Need to change 

Line#5491
```javascript
$item.$element.trigger( 'deselected.fu.repeaterList', $item );
```
change to
```javascript
self.$element.trigger( 'deselected.fu.repeaterList', $item );
```

**Comment by swilliamset** [comment]
fixed https://github.com/ExactTarget/fuelux/commit/836e66445bcd10fff60047a3ee8ddf08ab738342 
available with [3.6.5](https://github.com/ExactTarget/fuelux/milestones/3.6.5)
