### ISSUE TITLE
Additional repeater defaults

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1221]
We should set `preserveDataSourceOptions` to false explicitly in the defaults in order to document default options for those that read the source code to understand the API.

https://github.com/ExactTarget/fuelux/blob/master/js/repeater.js#L712

Are there any other options mentioned in the documentation that are not set in the repeater defaults object?

**Comment by swilliamset** [comment]
Do it for preserveDataSourceOptions. Agreed any defaults should be explicit. @kevinparkerson please assist with other defaults not explicitly included in the defaults.
