### ISSUE TITLE
Ability to have x, N.x, and N.N.x releases on CDN

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1237]
Use cases:

* Jsfiddles, codepens, etc
* Documentation sites (getfuelux.com, pages, etc)
* Small projects (non-enterprise)

Lowers cost of maintaining our disparate documentation efforts. Lowers cost of maintenance for small-potatoes sites where the cost of updating after each release is greater than the cost of fixing something when you happen to notice a release broke it.

**Comment by cormacmccarthy** [comment]
Talking with "the Aarons" right now to get our CDN configured correctly to allow for this. Will require uploading to a few different places on the CDN with each release instead of just one. Will require some CDN cache flushes at release time. Will require custom expire headers on *.x CDN targets to be much lower than the year we have them set for right now (one day? one week?).

**Comment by tomByrer** [comment]
[jsDelivr CDN](http://www.jsdelivr.com/) already has [versioning including `latest`](https://github.com/jsdelivr/jsdelivr#version-aliasing) built-in, with loads more features; why not use that instead?

**Comment by interactivellama** [comment]
Thanks for putting that on our radar, Tom. It's working for me: http://cdn.jsdelivr.net/fuelux/latest/js/fuelux.min.js

This works wonderfully, too. http://cdn.jsdelivr.net/g/jquery,bootstrap,fuelux
