### ISSUE TITLE
Show not-allowed cursor on all disabled items in repeater when disabled

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1239]
It only occurs on the page buttons and the views. It works on controls: selectlist, search, combobox, etc.

Adding enable/disable buttons to index.html would be good too.

Update: [Bootstrap disabled buttons](http://getbootstrap.com/css/#forms-control-disabled) does not have a not-allowed cursor applied to them. Adding question label.

Example of repeater in disabled state without `not-allowed` cursor.

![screenshot 2015-04-14 16 29 42](https://cloud.githubusercontent.com/assets/1290832/7146709/84ad8854-e2c3-11e4-86b3-2ec961d0fc21.png)

**Comment by interactivellama** [comment]
@jamin-hall Do we have disabled state cursor guidelines? 

This is really in the weeds. To view the current disabled state of the repeater, go here https://fuelux-dev.herokuapp.com/#repeater and you'll see it for a second or so on load. Reload to see it again and hover your mouse over elements.

**Comment by jamin-hall** [comment]
It’s loading too fast for me to see. I tried adding a disabled class to the row, but that didn’t seem to work either. Any other way I can see the current disabled state?

**Comment by jamin-hall** [comment]
Ok. I think I found a way to get it working. Had to remove the selectable class before disabled worked. Looks like the cursor was the standard default cursor on hover. For clickable rows the cursor changes to the pointer (the hand). I think I’ve seen some instances in the app where we’ve used the “not-allowed” cursor for disabled items, but we haven’t been consistent.

This is a really long way of saying I think whichever cursor we go with we should use consistently for all disabled states. I’d recommend sticking with “default” for disabled state, “pointer” for enabled & clickable states, and reserving the “not-allowed” for drag and drop or other interactions where certain things may be valid or invalid.

**Comment by interactivellama** [comment]
Thanks Jamin. 

Since the contents of the repeater is up to the developer custom cursors cannot be added/styled for it. We can only control the header and footer, but we will head that direction with those.

**Comment by interactivellama** [comment]
I'm closing this issue then, since we aren't going to add the not-allowed cursor.
