### ISSUE TITLE
Make wizard wrapper `div` overflow visible

### ISSUE THREAD

**Issue by vojtmen** [ExactTarget/fuelux#1241]
Is there any way how to set overflow: visible to Fuelux wizard top level div so the bigger content is shown correctly and wizard orientation header is shown correctly (it flows outside the wizard boarder in this case). FuelUX wizard obviously counts with overflow-x: hidden since it hides individual steps when moving across them.

Than the only option is to set overflow-x: hidden and overflow-y: auto (since it is the option supported by browsers - hidden + visible is not). But this looks really ugly then.

Simple scenario: I have wizard page with longer combobox in it.

**Comment by kevinparkerson** [comment]
@vojtmen I ran into this issue myself when working on an app! Will be addressing this soon, though it might require a bit of markup change.
