### ISSUE TITLE
Repeater deletes value of search field at the second ENTER keypress

### ISSUE THREAD

**Issue by vigna** [ExactTarget/fuelux#1244]
The repeater deletes the value of the search field is ENTER is pressed twice. You get back to an empty search field. You can check this easily on the example page. The first ENTER selects correctly a sublist, the second ENTER deletes the search field.

While this is only slightly puzzling in the example shown on the site, it becomes completely disconcerting if you attach a completer. When the user clicks on an entry of the completer, we trigger the repeater so that it shows the correct result. But if the user hits return again, the query is lost.

We think that hitting ENTER should just trigger the repeater (possibly checking that some element of the filter interface has changed).

**Comment by mbeard** [comment]
Note: this happens in the standalone search control, it's not specific to repeater.
