### ISSUE TITLE
WOFF2 font please

### ISSUE THREAD

**Issue by tomByrer** [ExactTarget/fuelux#1247]
[Smaller](https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a), & soon to be compatible with [1/2 of the (global) in-use browsers](http://caniuse.com/#feat=woff2).

Let me know if you want me to make a quicky conversion.

**Comment by interactivellama** [comment]
Pull requests are greatly welcomed. Our current WOFF is 1.3KB (non-gzipped).

Thanks. Tom!

**Comment by interactivellama** [comment]
This issue spurred the base64 embedding of the WOFF into the actual CSS which should be more performance friendly (at least untill HTTP/2 comes out!). See #1291.
