### ISSUE TITLE
Limit of items in tree

### ISSUE THREAD

**Issue by richerlariviere** [ExactTarget/fuelux#1252]
Is there a way to add a limit of selected items in a tree? I found nothing in the doc to do that. Thanks. If not it could be great to have it in a future update.

**Comment by interactivellama** [comment]
No, there currently is no limit. Would you be willing to provide a use case for this behavior, please?

As a work around, you could deselect (click) the last item selected if your array is "too long".

**Comment by richerlariviere** [comment]
Thanks, it worked!
