### ISSUE TITLE
Pre-checked / selected radios don't toggle elements

### ISSUE THREAD

**Issue by SuperSeb92** [ExactTarget/fuelux#1270]
Considering the following:

    <label data-initialize="radio">
        <input class="checked" data-toggle=".radioToggle" checked="checked" type="radio" value="option1">
        Toggle class element
    </label>
    
    <div class="radioToggle">Toggled</div>

I'd expect to see the toggled div, without having to un-check and re-check, is this intended behaviour?

I'm currently triggering this manually using $('.fuelux input[data-toggle]:checked').trigger('change');

**Comment by interactivellama** [comment]
This may be linked to #1287. Just wanted to connect the two.

Looks like we are not executing any class changes on init, only in `resetGroup` and `setCheckedState`
