### ISSUE TITLE
Refresh method needed

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1272]
Either implement #1148 or create a new method `refresh` that is effectively just closing and immediately disclosing the folder matching the passed in `id`. The recent tree changes "broke" the tree for people who were using the "open" method as a stop-gap to refresh the folder's contents.

Right now the only way to handle this is:

```Javascript
$tree.tree('close', '#folderId');
$tree.tree('disclose', '#folderId');
```

Would be nice to:

```Javascript
$tree.tree('refresh', '#folderId');
```

or (if we implement #1148):

```Javascript
$tree.tree('render', '#folderId');
```

**Comment by interactivellama** [comment]
The `refresh` method would essentially remove children, call the datasource, and populate, right?

`render` would be consistent with repeater.

**Comment by interactivellama** [comment]
See #1302.
