### ISSUE TITLE
Selectlist overflow if there are too many items

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [ExactTarget/fuelux#1279]
Issue was brought up if there were too many items no ability to scroll. Add an overflow property to the list and let individual instances of selectlist be controlled by a max height.

![image](https://cloud.githubusercontent.com/assets/6981338/7501688/f46bed4c-f403-11e4-9972-be9417ba8f63.png)

**Comment by interactivellama** [comment]
@BenjaminNeilDavis Should this be in combobox too?

**Comment by interactivellama** [comment]
Closing and I'll create another issue for combobox.
