### ISSUE TITLE
sync datepicker w updated pattern

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1281]
http://invis.io/BA29KQNSQ

@jamin-hall please provide final go ahead once this pattern is final

Selecting month and year should be more tile based versus the long scrolling

<img width="768" alt="screen shot 2015-09-11 at 4 58 48 pm" src="https://cloud.githubusercontent.com/assets/347227/9826195/7b7c0c2a-58a6-11e5-8f35-5796b979fa1b.png">

**Comment by interactivellama** [comment]
@jamin-hall I think everyone may need to be invited to the salesforce.invisionapp.com org on InVision.

**Comment by jamin-hall** [comment]
@interactivellama looks like a few members from the UXA team haven't been added to the Salesforce enterprise account. @swilliamset can you help me get a list together for JD? He's the only one with admin privileges to get people added.

In the meantime, try this link instead: http://invis.io/BA29KQNSQ

**Comment by swilliamset** [comment]
the share url you provide will suffice for the time being. thank you.

**Comment by swilliamset** [comment]
fyi I updated the issue to the share url
