### ISSUE TITLE
Scheduler Sets Start dateTime to the Reoccuring Until Date  no matter what

### ISSUE THREAD

**Issue by razor247** [ExactTarget/fuelux#1293]
The Scheduler control in version 3.7.1+ sets its StartDateTime datepicker control to the Reoccuring Until DateTime if you initialize scheduler with a StartDateTime, TimeZone, and ReoccurancePattern. You should remove line 6999 and then change line 7000 to use the 'temp' variable instead of the startDate variable. If you don't do this you'll never be able to initialize the start datetime with a different datetime than the Reoccurance Until date. The lines numbers are from version 3.7.1 however the same problem is in 3.7.2

**Comment by dkilgore** [comment]
Confirmed that this issue is present in 3.7.2.
