### ISSUE TITLE
Horizontal Scrolling and Column Selection on Repeaters

### ISSUE THREAD

**Issue by rathinaganesh** [ExactTarget/fuelux#1295]
Hi,

I was wondering if the Fuelux library have horizontal scrolling and a feature to pick and choose the columns to be displayed on the Repeater dynamically? That is show/hide columns dynamically on the Repeater.

Thanks.

**Comment by interactivellama** [comment]
@kevinparkerson I think is the way, off the top of my head. I'm out of the office right now.

Set `list_columnSizing` to false, you may want to set a width to the column inside the `columns` array in your datasource. Show/hide columns can be controlled by calling the `render` method with a new `columns` array.

See http://getfuelux.com/extensions.html#bundled-extensions-list-datasource for more details.
