### ISSUE TITLE
Pillbox onKeyDown callback should close suggestions list if data is null or empty

### ISSUE THREAD

**Issue by stefann42** [ExactTarget/fuelux#1298]
A frequent type-ahead scenario is when user types something that doesn't generate any results. In this case previous results need to be cleared to indicate current user-typed text doesn't correspond to any choices. Unfortunately _openSuggestions doesn't handle this case as of 3.7.2.

**Comment by swilliamset** [comment]
Else should be added here https://github.com/ExactTarget/fuelux/blob/7f9caac51abc952251401632816d0de39a5578e0/js/pillbox.js#L656
