### ISSUE TITLE
Tree refresh method

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1302]
I need a `.tree(‘refresh’, folderId)` method.

or, at the very least, a `.tree(‘clearCache’)` method.

or, preferably all three of `.tree(‘clearCache’)`, `.tree(‘refresh’)`, and `.tree(‘refresh’, folderId)` and/or `.tree(‘refresh’, $folder)` methods

`.tree(‘refresh’, folderId)` re-queries the dataSource (regardless of your options.cache settings) for the children of the specified folderId. It should disclose as many of the children that were previously disclosed as possible.

`.tree('clearCache')` clears your local cache of the data (useful when options.cache is `true`, which is the default)

`.tree(‘refresh’)` re-queries the dataSource (regardless of your options.cache settings) for the entire tree. It should disclose as many of the children that were previously disclosed as possible.

**Comment by swilliamset** [comment]
agreed approach is to create/expose refresh method

**Comment by interactivellama** [comment]
After talking to @cormacmccarthy: The purpose of this feature was to manipulate a tree node to change it's content (as in rename) and/or attributes. We have decided to shelve this feature.
