### ISSUE TITLE
Repeater list plugin needs an API for selecting all items

### ISSUE THREAD

**Issue by robross0606** [ExactTarget/fuelux#1304]
I don't believe there is an option to select all the items in a repeater.  Items can be selected based on limited search criteria, but I don't believe wildcards are supported there either.  Is there any current way to use the API to select all repeater list items?

**Comment by robross0606** [comment]
I was able to work around this by artificially adding a dummy property for all items that could then be used as selection criteria in the current API.  However, that is still a clunky option.

**Comment by kevinparkerson** [comment]
@robross0606 interesting point, we will have to add a means to select all items to both `repeater_list` and `repeater_thumbnail` plugins. Thanks!

**Comment by BenjaminNeilDavis** [comment]
You can now do this with multi-select enabled. list_selectable: 'multi'
http://getfuelux.com/extensions.html#bundled-extensions-list-options
