### ISSUE TITLE
Scheduler Monthly/Yearly Radio Buttons will not default checked correctly

### ISSUE THREAD

**Issue by razor247** [ExactTarget/fuelux#1306]
Scheduler Monthly and Yearly Radio Buttons choices won't default select properly unless the selected radio button is the last one in the group in the HTML. There is a bug with the calling of the ResetGroup() function for each radio button created in the group upon SetInitialState(). This means every call to create a radio button unselects any previous ones in the group. If you set any radio button in a group except the last on to default selected it won't appear selected even thou the hidden radio button is indeed selected. Even your demo page displays the problems notice how nothing is selected in the reoccurring demo when you switch to Yearly reoccurring but the hidden radio actually is selected and you can't see it? This is going to be my fourth bug report with the exact code to change on the scheduler any kind of timeframe?  For this one you need to remove the ResetGroup() function call. It appears to serve no purpose other than to break the initialization because SetChecked() executes that exact same code that's in ResetGroup.....again

**Comment by swilliamset** [comment]
If you wouldn't mind providing an example (codepen, jsfiddle, jsbin, etc) we would be happy to take a closer look.

**Comment by kevinparkerson** [comment]
This is a problem with the radio control, not the scheduler. Thanks for pointing this out @razor247. Submitting a fix soon.

**Comment by razor247** [comment]
Ok awesome..I did find that you can’t remove that function. Instead I passed an optional Initialize flag so that function doesn’t get called on initialize but it will be called on all remaining calls to checked….

**Comment by razor247** [comment]
Stephen Williams from fuelux just emailed me after your email and said he verified the problem and is working on a fix.

 

You don’t really need a jsfiddle..Just look on your demo page at the Live Schedule sample. Chose Yearly reoccurance..notice there are two radio button 

Options neither of which appears to be selected. However the top option is indeed selected if you look at the hidden radio button. The problem is

In the radio initialization code. That code wipes out all initial settings and will only retain the last radio button in the group’s settings due to the resetGroup  function being called.

**Comment by interactivellama** [comment]
This looks to be the cause of #1287 too. "Checked radio on init only works if it is last"
