### ISSUE TITLE
[Repeater] Fire pageChange event

### ISSUE THREAD

**Issue by alxy** [ExactTarget/fuelux#1317]
I think I found a bug in the following event: `pageChanged.fu.repeater`

https://github.com/ExactTarget/fuelux/blob/3.7.x/js/repeater.js#L89-L91
I think it is only fired if the user changes the page using the so-called `primaryPaging`, but not if he uses the regular previous/next arrows. Also, these events should be documented in the documentation.

My JS skills are not good enough to provide a PR for this :(

**Comment by interactivellama** [comment]
I don't have a timeframe for fixing the bug, but we will update the repeater documentation soon. See #1324.
