### ISSUE TITLE
[Wizard] Needs validation hook

### ISSUE THREAD

**Issue by scott-joe-williams** [ExactTarget/fuelux#1320]
We're validating the step's contents via an API call, so the "next" trigger is happening as a callback. There are other products needing dynamic/async based roadblocking and next step triggering.

Specifics to come.

**Comment by scott-joe-williams** [comment]
@jbarngr ^

**Comment by scott-joe-williams** [comment]
@kevinparkerson @interactivellama Thoughts? This is a blocker for both MobilePush and GroupConnect.

**Comment by mbeard** [comment]
Why can't you cancel/suppress the `actionclicked` event and then call the `next` method when validation is successful?

**Comment by scott-joe-williams** [comment]
@kjaenicke ^

**Comment by jbarngr** [comment]
@mbeard Providing a callback at least gives the developer a method to internally override the default functionality, without having to completely override all functionality built in the wizard. My main reason for this is the ability to easily prevent going to the next step while waiting on a server side response when saving draft states between each step.

**Comment by mbeard** [comment]
Canceling the event it's really completely overriding the entire wizard.  It's not really doing anything other than preventing the `next` method from being called internally...so you can call subsequently call it when you need to - you can see that [here](https://github.com/ExactTarget/fuelux/blob/master/js/wizard.js#L261-L265)

Presumably, your already doing some logic on step change to determine what step you are on (to know if you need to do validation at all, or which route you need to call to validate if you have validation on multiple steps.  This would just be one additional snippet to cancel the event.

With a callback, I think you'd have to handle both success conditions (calling next), in addition to error conditions (remaining on the page), and we'd have to deal with the callback not returning at all (if there was some sort of scripting error).  I guess what I'm saying is that I don't see the callback as any more elegant than solution we have to support this now.

**Comment by scott-joe-williams** [comment]
@jbarngr Does that help?

**Comment by jbarngr** [comment]
I would like the wizard to keep track of a boolean state that it checks to make sure that the next function can initiate the .next function or that can be checked in the next function and pause the step process.

**Comment by nkirkes** [comment]
Guys, can we all get in a room for a few minutes to whiteboard as a team?

**Comment by nkirkes** [comment]
*"we all" meaning, whoever needs to be involved?

**Comment by scott-joe-williams** [comment]
A meeting is on the books.

*Scott Williams*

*Sr. Front-End Engineer, UX Architecture*UXDS, Salesforce Marketing Cloud

**Comment by interactivellama** [comment]
Conversation has been transferred to #1347.
