### ISSUE TITLE
Tree buttons submit HTML form due to lack of type attribute

### ISSUE THREAD

**Issue by richerlariviere** [ExactTarget/fuelux#1323]
I have a tree inside a form. Unfortunately when I select an element, a submit event is triggered. There is no problem when put it outside the form. The form is a pretty standard Cakephp 2.x form.

I can't paste a code example for the moment. 

Btw, keep working hard, I love your plugin.

**Comment by interactivellama** [comment]
Thanks. I was able to duplicate. No JS fiddle needed.

**Comment by interactivellama** [comment]
Add the `type` to the button in the item/branch template. Buttons without a type default to submit.
`<button type="button" class="tree-item-name">`

**Comment by interactivellama** [comment]
It would be a good idea to add this to the default markup.

**Comment by richerlariviere** [comment]
Cool! I looked at the code and it seems to be correct. I'm happy you found the problem.
