### ISSUE TITLE
Document repeater events

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1324]
Gap analysis has showed that many repeater events are missing and need to be added to documentation.
http://getfuelux.com/extensions.html#bundled-extensions-list-events

Add events to general repeater also.
http://getfuelux.com/javascript.html#repeater

Thanks, @4chen500!

**Comment by 4chen500** [comment]
@interactivellama In your above link, that is only the extension events, the standard repeater events are missing also, fyi.

**Comment by kevinparkerson** [comment]
@4chen500 I might not get to this until later this week. In the meantime, searching for `.trigger` inside the repeater.js, repeater-list.js, and repeater-thumbnail.js files will show you possible events you can listen for.

**Comment by 4chen500** [comment]
@interactivellama, @kevinparkerson 

No worries, I can just look in the source. It does seem like this documentation existed at one point, but this isn't a blocker for me in any way. Thanks!

**Comment by cormacmccarthy** [comment]
+1 I was just coming to submit this issue also...
