### ISSUE TITLE
Pillbox should attach a hidden input element with each pill

### ISSUE THREAD

**Issue by J-F-Liu** [ExactTarget/fuelux#1330]
Pillbox should attach a hidden input element with each pill, so that when Pillbox is used in a form we can get the value list without writing script.
The name of hidden input can be set with a data attribute like data-field-name="..."

**Comment by interactivellama** [comment]
With the current set up, we would recommend using something like [this answer](http://stackoverflow.com/questions/29628271/how-can-i-use-fuel-ux-pillbox-as-an-element-in-a-html-form/29630297#29630297) to "How can I use Fuel UX pillbox as an element in a HTML form?" on StackOverflow which as you say uses additional scripting.

Although we do try to support form submission in this library, we also need to balance that with keeping the markup clean for those that are primarily build JavaScript-based SPAs (which include our internal clients).

The team may be open to a PR that would make the updating the pill's hidden input supported, but optional. I'm guessing this would include modifying the `this.$pillHTML` string via an initialization option.
