### ISSUE TITLE
Add "MINUTELY" AND "SECONDLY" support

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1337]
@jamin-hall Request has been made to support `MINUTELY` which is in the [the iCal spec](http://www.kanzaki.com/docs/ical/rrule.html). `SECONDLY` should probably be supported, since it's just text injection and we'll be in there. It remains to be seen whether `SECONDLY` should be present in the dropdown by default in the markup.

@ryanwilliamsET Minutely and secondly for "repeat" dropdown options seem archaic in this instance. See [StackExchange's English forum](http://english.stackexchange.com/questions/3091/weekly-daily-hourly-minutely). Internal proponents support "Every minute" and "Every second". We are somewhat limited in our character length, but those should work. See [deployed scheduler UI](https://fuelux-dev.herokuapp.com/#scheduler).

**Comment by swilliamset** [comment]
removed "hold" label. functionality makes since and options can be removed by excluding values in the select list. only outstanding question to design would be recommend terms other than "minutely" and "secondly".

**Comment by interactivellama** [comment]
Implemented in #1338. Awaiting @ryanwilliamsET and @jamin-hall 's thoughts.

**Comment by interactivellama** [comment]
Reopening due to micro-copy discussion.

**Comment by interactivellama** [comment]
Response from @ryanwilliamsET:
>Every Minute or Every Second should work just fine. If you need to shave off a character or two, you might be able to get away with Per Minute and Per Second.

**Comment by swilliamset** [comment]
i'll make the update and submit a pr

**Comment by mbeard** [comment]
If we use "Every Minute / Every Second", won't the entire row label say something like:
Repeat Every Minute every x minute(s)

**Comment by interactivellama** [comment]
Yes, @swilliamset and I hesitant to do that and @swilliamset is getting clarification outside GH.
