### ISSUE TITLE
Scheduler does not fire changed.fu.scheduler when calendar dates are clicked

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux#1344]
![screen shot 2015-06-09 at 2 04 50 pm](https://cloud.githubusercontent.com/assets/1205242/8065665/dea508e6-0eb0-11e5-939e-d168700729c0.png)

When clicking on a date in the calendar the changed.fu.scheduler event does not fire.

**Comment by interactivellama** [comment]
To the best of my knowledge, `changed` events are only fired on inputs when `onBlur` occurs in this library. Looks like datepicker's `dateClicked` is not chained to trigger `changed.fu.scheduler`. Working on a PR for this. 

@kevinparkerson @swilliamset Is there any reason we wouldn't want datepicker's `dateClicked` to not trigger `changed.fu.scheduler`?

We are currently working under the premise that the date is really not changed until the focus leaves the datepicker input either via tab or outside mouse click--this reasoning is why the focus is given to the input after the date is clicked. The alternative would be to create a `dateClicked` event which would be more in line with the spirit of the API for `datepicker`.

**Comment by kevinparkerson** [comment]
seems to me like changed.fu.scheduler should be fired upon a dateClick, and that it was simply overlooked

**Comment by swilliamset** [comment]
agree with @kevinparkerson. simplest solution.
