### ISSUE TITLE
An empty selectlist needs to not look like a scrunched-up dropdown.

### ISSUE THREAD

**Issue by kevinparkerson** [ExactTarget/fuelux#1349]
An empty selectlist should still have a min-height and min-width so that it is not too visually small. Currently if no items are present the overall size is approximately 42 pixels in width by 14 pixels in height. The min-height should probably be the standard height of the selectlist if items are present and the min-width perhaps twice that of the min-height.

**Comment by interactivellama** [comment]
I would think an empty select list would be disabled and have a "No items/value=null" type of selected label. However, I could see an empty combobox needing to be supported. 

We could also put a min-height on all dropdowns if that's the problem.

**Comment by jamin-hall** [comment]
+1 for disabling the dropdown. Keith's team recently discovered this behavior and thought it was a bug.

**Comment by interactivellama** [comment]
@kevinparkerson I don't want to lock people in, but I guess we could add an init option to opt out. I think auto-disabling an empty `selectlist` would be a good default. It would be more user-centered.

**Comment by interactivellama** [comment]
Keith's team found a complicated bug (from the user's standpoint) with the combobox in repeater. It has to do with the paging combobox not "working correctly" when there are not items found or there is only 1 page. I will get more details and post another issue.

**Comment by interactivellama** [comment]
@jamin-hall @kevinparkerson I've PR'd two proposals for combobox and selectlist. 

We still need to look at the pattern for repeater. I was asking around the department and some peeps were thinking that the combobox or selectlist for paging should only be text if it is `0 of 0 pages` or `1 of 1 pages`.

**Comment by kevinparkerson** [comment]
@interactivellama I think disabling the selectlist is ok, but it also needs to still be the correct size despite having no content. When I created the issue, the selectlist appears like a very small button because it's height is entirely determined by the content. A min-height style would probably fix that :)
