### ISSUE TITLE
Conflict with Bootstrap mixin

### ISSUE THREAD

**Issue by tompazourek** [ExactTarget/fuelux#1354]
I use the source LESS of Bootstrap library (v3.3.4) to customize it, it declares the following mixin called `.vertical` (in mixins/gradients.less):

    #gradient {
        .vertical(@start-color: #555; @end-color: #333; @start-percent: 0%; @end-percent: 100%) {
            background-image: -webkit-linear-gradient(top, @start-color @start-percent, @end-color @end-percent);  // Safari 5.1-6, Chrome 10+
            background-image: -o-linear-gradient(top, @start-color @start-percent, @end-color @end-percent);  // Opera 12
            background-image: linear-gradient(to bottom, @start-color @start-percent, @end-color @end-percent); // Standard, IE10, Firefox 16+, Opera 12.10+, Safari 7+, Chrome 26+
            background-repeat: repeat-x;
            filter: e(%("progid:DXImageTransform.Microsoft.gradient(startColorstr='%d', endColorstr='%d', GradientType=0)",argb(@start-color),argb(@end-color))); // IE9 and down
        }
     }

I also try to use the FuelUX library (v3.8.0). It also contains mixin called `.vertical` (in mixins.less):

    #gradient {
        .vertical(@startColor: #555, @endColor: #333) {
            background-color: mix(@startColor, @endColor, 60%);
            background-image: -moz-linear-gradient(top, @startColor, @endColor); // FF 3.6+
            background-image: -webkit-gradient(linear, 0 0, 0 100%, from(@startColor), to(@endColor)); // Safari 4+, Chrome 2+
            background-image: -webkit-linear-gradient(top, @startColor, @endColor); // Safari 5.1+, Chrome 10+
            background-image: -o-linear-gradient(top, @startColor, @endColor); // Opera 11.10
            background-image: linear-gradient(to bottom, @startColor, @endColor); // Standard, IE10
            background-repeat: repeat-x;
            filter: e(%("progid:DXImageTransform.Microsoft.gradient(startColorstr='%d', endColorstr='%d', GradientType=0)",argb(@startColor),argb(@endColor))); // IE9 and down
        }
    }

When I reference both Bootstrap LESS files and FuelUX LESS files, I get this error when trying to compile:

    Named argument for .vertical @startColor not found in file \fuelux\less\repeater-list.less line no. 103

How can I solve this issue?

**Comment by interactivellama** [comment]
At this time, the only way to use Fuel UX and Bootstrap within one CSS file is through concatenation, such as [grunt-concat](https://github.com/gruntjs/grunt-contrib-concat) and not with the LESS compiler. The team is open to changing this through pull requests though.

**Comment by interactivellama** [comment]
@tompazourek I looked into this closer and I am not receiving errors with the following grunt config:

```
dist: {
				options: {
					strictMath: true,
					sourceMap: true,
					outputSourceFiles: true,
					sourceMapURL: '<%= pkg.name %>.css.map',
					sourceMapFilename: 'dist/css/<%= pkg.name %>.css.map'
				},
				files: {
					'dist/css/fuelux.css': ['bower_components/bootstrap/less/bootstrap.less','less/fuelux.less']
				}
			},
```

I do get that error when I do the following within the same LESS file:
```
@charset "UTF-8";

// Core variables and mixins
@import "../bower_components/bootstrap/less/variables.less";
@import "../bower_components/bootstrap/less/mixins.less";
// Reset ../bower_components/bootstrap/less/and dependencies
@import "../bower_components/bootstrap/less/normalize.less";
@import "../bower_components/bootstrap/less/print.less";
@import "../bower_components/bootstrap/less/glyphicons.less";
// Core C../bower_components/bootstrap/less/SS
@import "../bower_components/bootstrap/less/scaffolding.less";
@import "../bower_components/bootstrap/less/type.less";
@import "../bower_components/bootstrap/less/code.less";
@import "../bower_components/bootstrap/less/grid.less";
@import "../bower_components/bootstrap/less/tables.less";
@import "../bower_components/bootstrap/less/forms.less";
@import "../bower_components/bootstrap/less/buttons.less";
// Compon../bower_components/bootstrap/less/ents
@import "../bower_components/bootstrap/less/component-animations.less";
@import "../bower_components/bootstrap/less/dropdowns.less";
@import "../bower_components/bootstrap/less/button-groups.less";
@import "../bower_components/bootstrap/less/input-groups.less";
@import "../bower_components/bootstrap/less/navs.less";
@import "../bower_components/bootstrap/less/navbar.less";
@import "../bower_components/bootstrap/less/breadcrumbs.less";
@import "../bower_components/bootstrap/less/pagination.less";
@import "../bower_components/bootstrap/less/pager.less";
@import "../bower_components/bootstrap/less/labels.less";
@import "../bower_components/bootstrap/less/badges.less";
@import "../bower_components/bootstrap/less/jumbotron.less";
@import "../bower_components/bootstrap/less/thumbnails.less";
@import "../bower_components/bootstrap/less/alerts.less";
@import "../bower_components/bootstrap/less/progress-bars.less";
@import "../bower_components/bootstrap/less/media.less";
@import "../bower_components/bootstrap/less/list-group.less";
@import "../bower_components/bootstrap/less/panels.less";
@import "../bower_components/bootstrap/less/responsive-embed.less";
@import "../bower_components/bootstrap/less/wells.less";
@import "../bower_components/bootstrap/less/close.less";
// Compon../bower_components/bootstrap/less/ents w/ JavaScript
@import "../bower_components/bootstrap/less/modals.less";
@import "../bower_components/bootstrap/less/tooltip.less";
@import "../bower_components/bootstrap/less/popovers.less";
@import "../bower_components/bootstrap/less/carousel.less";
// Utilit../bower_components/bootstrap/less/y classes
@import "../bower_components/bootstrap/less/utilities.less";
@import "../bower_components/bootstrap/less/responsive-utilities.less";


// Core variables, mixins, and icons
@import "variables.less";	// Modify this for custom colors, font-sizes, etc
@import "mixins.less";
@import "icons.less";

// Fuel UX controls
@import "forms.less"; // forms.less contains code shared between form elements.
@import "checkbox.less"; // Checkbox styles that will be deprecated.
@import "checkbox-no-js.less"; // Checkbox styles that are not dependant upon custom javascript controls.
@import "radio.less"; // Radio styles that will be deprecated.
@import "radio-no-js.less";  // Radio styles that are not dependant upon custom javascript controls.
@import "combobox.less";
@import "datepicker.less";
@import "infinite-scroll.less";
@import "intelligent-dropdown.less";
@import "loader.less";
@import "pillbox.less";
@import "placard.less";
@import "repeater.less";
@import "repeater-list.less";
@import "repeater-thumbnail.less";
@import "spinbox.less";
@import "scheduler.less";
@import "search.less";
@import "selectlist.less";
@import "tree.less";
@import "wizard.less";
@import "utility.less";
```

**Comment by interactivellama** [comment]
My PR #1362 should fix your issue. I still would recommend using `@import` instead of bringing in all the LESS files directly.
