### ISSUE TITLE
Repeater pagination if zero (that is no items) or one page exist

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1359]
Some thought needs to be put into deciding how to display the pagination in the repeater footer.

One option is that paging should only be text if it is 0 of 0 pages or 1 of 1 pages. We may still want "combobox" padding with a border though so that the UI doesn't jump around.

Cross reference with #1349.

**Comment by cormacmccarthy** [comment]
This has been resolved. Thanks.
