### ISSUE TITLE
Pillbox added.fu.pillbox event not triggered for items added through addItems api

### ISSUE THREAD

**Issue by ikilledthecat** [ExactTarget/fuelux#1361]
The event 'added.fu.pillbox' does not get fired because it is wrapped inside an if condition checking for isInternal (line 4398 pillbox.js) variable that doesn't get set and need to hook into this event for my use case. I have removed this check but I have a couple of question:
1. What is advantage of not triggering an event if called programmatically?
2. Is there any downside to what I'm doing? While nothing seems to be broken with this change is there anything I should be aware of?

**Comment by cormacmccarthy** [comment]
We will be addressing this. Thank you!
