### ISSUE TITLE
Issue with Radio Buttons + highlight container

### ISSUE THREAD

**Issue by jonhibbard** [ExactTarget/fuelux#1365]
There appears to be a sporadic bug that we can see when using multiple Radio components together when inline with a `highlight` container div.

Steps to duplicate:
* Click the radio button Option 1 (which has a dropdown menu inline next to it) as soon s the page loads (no hesitation)
* Move your mouse to trigger the `onmouseout` (assumed) 
* The radio button flickers and then becomes unchecked
* Try to click the radio button but notice you are unable to do so.  You'll have to first click a different radio button and then you can once again re-select this first radio button.

Additional information:
* Removing the `highlight` class seems to fix the issue
* If you don't remove the `highlight` class, you can instead do the following to ensure this bug doesn't occur: 
  * Place your mouse over each radio button but do not click.  Do this slowly. 
  * Once you've done this for all 3 radio buttons, you can now click the first radio button without any issue.

Example to duplicate the problem:
```html
<div className="col-sm-10" ref="options">
	<div className="form-group">
		<div className="radio highlight radio-send-method" data-initialize="radio">
			<label className="radio-custom radio-inline" data-initialize="radio">
				<input className="sr-only" name="options" ref="opt1" type="radio" value="opt1" />
				<span  className="opt-label">Option 1</span>
				<div id="opt1-selectlist" className="btn-group" ref="opt1Select" data-initialize="selectlist">
					<button className="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
						<span className="selected-label"></span>
						<span className="caret"></span>
					</button>
					<ul className="dropdown-menu" role="menu">
						{ options }
					</ul>
				</div>
			</label>
		</div>

		<div className="radio highlight radio-send-method" data-initialize="radio">
			<label className="radio-custom radio-inline" data-initialize="radio">
				<input type="radio" name="options" ref="opt2" className="sr-only" value="opt2" />
				<span  className="opt-label">Option 2</span>
				<input type="text" className="opt2-input" value="" />
				<button className="btn btn-default">create</button>
			</label>
		</div>

		<div className="radio highlight radio-send-method" data-initialize="radio">
			<label className="radio-custom radio-inline" data-initialize="radio">
				<input type="radio" name="options" ref="opt3" className="sr-only" value="opt3" />
				<span className="opt-label">Option 3</span>
				<span ref="lexis" className="lexis" data-lexis-cid="lkakasj-d-fha"></span>
			</label>
		</div>
	</div>
</div>

```

The above renders something like:
```
o Option 1 [dropdown]
o Option 2 [ input box          ]
o Option 3 
```

Additional Information:
* jQuery JavaScript Library v2.1.4
* jQuery UI Core 1.11.0
* Underscore.js 1.8.3
* There are no custom `onmouseover` or `onclick` listeners

**Comment by interactivellama** [comment]
Thank you for the extended debugging. We will look into it. Have you tried not using the `data-initialize="radio"` and using .radio() method to intitialize. We have not done extensive testing with other controls within our radio labels.

**Comment by jonhibbard** [comment]
@interactivellama worked like a charm, thanks!  Apologies for the lengthy report.  Thanks again
