### ISSUE TITLE
wizard mobile support

### ISSUE THREAD

**Issue by werddomain** [ExactTarget/fuelux#1376]
Hi, the wizard is very nice! but it's not responsive on mobile ...
i think i will override the style to make this scrollable ... then auto scroll to the selected element ...

I just want you know it don't show correctly ...

**Comment by werddomain** [comment]
i have hacked it myself.
Hope this help the project. I dont know how github work, if you can add it on the next version it will be nice :)

JS:
//This is to not call the resize on each resize event, it will only call it on the last event.
var waitForFinalEvent = (function () {
    var timers = {};
    var Start = function (callback, ms, uniqueId) {
        if (!uniqueId) {
            uniqueId = "Don't call this twice without a uniqueId";
        }
        if (timers[uniqueId]) {
            clearTimeout(timers[uniqueId]);
        }
        timers[uniqueId] = setTimeout(callback, ms);
    },
		Stop = function (uniqueId) {
		    clearTimeout(timers[uniqueId]);
		};
    return {
        Start: Start,
        Stop: Stop
    };
})();
 var wizzard = $('#wizard');
    var steps = $('.steps-container .steps li', wizzard);
    var cc = $('.fuelux .wizard .steps-container');
    var container = $('ul.steps, .fuelux .wizard > .steps-container > ul.steps', wizzard);
    var width = 40;
    container.css('height', 43);
    function ResizeWizzard() {
        waitForFinalEvent.Start(function () {


            var active = $("ul.steps li.active");
            width = 40;
           //Calculate the total width of steps, 40 is margin or padding of 20*2
            steps.each(function () {
                width += $(this).width() + 40;
            });

            container.css('width', width);
            var overflow = wizzard.width() < width;
            if (overflow) {
               //Here we scroll to the active step
                cc.animate({
                    scrollLeft: active.offset().left - cc.offset().left + cc.scrollLeft()
                });
                cc.addClass('Scroll');
            }
            else {

                cc.removeClass('Scroll');
            }
        }, 200, "WizzardResize");
    }
    ResizeWizzard();
    wizzard.resize(function () { ResizeWizzard(); });
    $(window).resize(function () { ResizeWizzard(); });
    $(window).on("orientationchange", function () { ResizeWizzard(); });

CSS:
.fuelux .wizard .steps-container.Scroll {
overflow:hidden;
overflow-x:auto;
overflow-y:no-content;
}

**Comment by alexweissman** [comment]
I'd like to see a responsive wizard as well!
