### ISSUE TITLE
Placard documentation of events

### ISSUE THREAD

**Issue by jbarngr** [ExactTarget/fuelux#1383]
Currently the placard documentation for events differs from the code. 
![screen shot 2015-07-02 at 9 30 38 pm](https://cloud.githubusercontent.com/assets/915237/8491067/b9128a96-2101-11e5-810a-359f7a2c53a5.png)

Documented => coded (line number)
show.fu.placard => shown.fu.placard (230)
hide.fu.placard => hidden.fu.placard (168)
accept.fu.placard => accept (54, 86)
cancel.fu.placard => cancel (56, 89)

**Comment by interactivellama** [comment]
Thanks @jbarngr. `shown` and `hidden` have been updated in the documentation. The team will need to discuss the other two.
