### ISSUE TITLE
Datepicker "scrolling year UI" is keyboard inaccessible

### ISSUE THREAD

**Issue by lei32wang** [ExactTarget/fuelux#1395]
Hi ,

I have some issues regarding tab-key navigating for the datapicker . it seems that I could not get  the  keyboard focus on the back + select buttons selection with tab key(in the month/year selection window).  The reason I believe that the focus is always on the year's selection as no end for the year loop ?

Also I have one more request, how to set the start year ? for example, from the year 1900. it seems that I could not use the restricted { from: '01/01/1900', to: '' } , the dates before the 1900 are still showing up  just not selectable.. 

Could you please take a look at this ?  thanks in advance.

**Comment by interactivellama** [comment]
With the restricted dates, try this:
```
$('#myDatepicker').datepicker({
	allowPastDates: true,
	restricted: [{
		from: -Infinity,
		to: '01/01/1900'
	}]
});
```

However, I tested it myself and the years are still selectable as you say. No days are though. The "scrolling years UI" is not checked for validity, just the final day selection.

Yes, there is a tabbing issue present with the "wheel year selection". It is not fully accessible. Do you have any suggestions on how you would want it to work? We are considering changing the UI for the month/year selection. It would be closer to the {Fuel UX 2 implementation](http://getfuelux.com/2.6/#datepicker).

**Comment by lei32wang** [comment]
Normally the focus should move from control to control with tab key and navigation inside the list should happen with cursor keys I guess.

I wonder does the fuelux datapicker provide the ability to configure the start year ? I would prefer the start year from the 1900 and the dates before 1900 should not be visible in the datepicker.

**Comment by interactivellama** [comment]
I think that would be a great idea for keyboard accessibility. Override the default tab with focusing on the select button, and binding keyboard arrows to the switching years and months.

You can set the default year and restrict which dates can be selected, but the years will scroll back to 0 A.D. (I think) if asked to.

**Comment by lei32wang** [comment]
I wonder if you would implement it or leave me to try ? if you could please let me know when.

As you are considering changing the month/year selection mechanism , it would be helpful to let me know when that might happen  then to see how that schedule fits to our needs.

**Comment by interactivellama** [comment]
We'd love to see a pull request with keyboard actions. Thanks!

**Comment by cormacmccarthy** [comment]
Thank you for the information. This behavior is changing in an upcoming release and we will be addressing accessibility.
