### ISSUE TITLE
Selectlist judders on load in documentation

### ISSUE THREAD

**Issue by shaneparsons** [ExactTarget/fuelux#1397]
For the most part, when a page first loads the selectlist starts off small for a second or two before being populated, creating a flicker / judder.

I found adding the following CSS fixed it.

```
.fuelux .selectlist .btn {
   min-height: 34px;
}
```

**Comment by interactivellama** [comment]
It should have the `&nbsp;` within it and have the height of the text of the `&nbsp;` present on page load.

**Comment by shaneparsons** [comment]
This snapshot was taken from the demo site:
http://getfuelux.com/javascript.html#selectlist

![screen shot 2015-07-13 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/5495493/8654466/865581d0-2958-11e5-9d15-957402453e9e.png)

**Comment by interactivellama** [comment]
Looks like our sample code needs the `&nbsp;` Thanks for pointing that out!

This will fix it. Fee free to pull request in the gh-pages branch and I'll merge.
```
<div class="btn-group selectlist" data-resize="auto" data-initialize="selectlist" id="mySelectlist">
  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button">
    <span class="selected-label">&nbsp;</span>
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li data-value="1"><a href="#">One</a></li>
    ...
  </ul>
  <input class="hidden hidden-field" name="mySelectlist" readonly="readonly" aria-hidden="true" type="text"/>
</div>
```

**Comment by shaneparsons** [comment]
#1399

**Comment by kevinparkerson** [comment]
@interactivellama this is what I was referring to with #1349

**Comment by shaneparsons** [comment]
This is officially fixed from my point of view so I'll let you guys close it when you're done with it.
Thanks!

**Comment by interactivellama** [comment]
@kevinparkerson Oh I thought we were talking about dropdown menus!
