### ISSUE TITLE
Date&Time selection support in the datapicker

### ISSUE THREAD

**Issue by lei32wang** [ExactTarget/fuelux#1403]
I would like to know does the datapicker support the Date&time selection ?  there may be the UI in which the user could  select the date and also the hour/minute spinners and etc .

**Comment by interactivellama** [comment]
Sorry, we don't have any time-setting spinboxes. The closest thing would be [scheduler](http://getfuelux.com/javascript.html#scheduler) and hide the repeat section if you don't need it.

Our internal use case would be sending something like an email or setting a calendar event and users will probably be fine with a `combobox` like the one used in `scheduler`.
