### ISSUE TITLE
Placard not firing on Firefox

### ISSUE THREAD

**Issue by dcoghill-salesforce** [ExactTarget/fuelux#1416]
Great platform!

Having trouble getting placards to work on Firefox. Working flawlessly in Chrome, but in Firefox, the text input inside the placard cannot be left-clicked - the only way to give it focus is to tab to the input, or right click the input.

Using Chrome v44 and Firefox v39, with FuelUX v3.7.2.

Any pointers and/or fixes would be greatly appreciated.

Sample HTML:

    <ul class="ui-sortable">
        <li class="ui-sortable-handle">
            <p class="title">Program Name</p>
            <div class="placard" data-initialize="placard" id="1437534987">
                <div style="bottom: -62px;" class="placard-popup"></div>
                
                <input class="form-control placard-field" placeholder="Program Note" name="lifecycle_program_note[]" value="" type="text">
                
               <div class="placard-footer">
                    <div class="text-left small" style="padding-bottom:6px;">
                        <label><input name="lifecycle_program_exists_checkbox[]" value="1" title="Already implemented" type="checkbox"> Already implemented</label>
                    </div>
                    <a href="#" class="btn btn-danger btn-xs placard-cancel pull-left remove_program">Remove</a>
                    <a class="placard-cancel" href="#">Cancel</a>
                    <button class="btn btn-primary btn-xs placard-accept" type="button">OK</button>
                </div>
            </div>
        </li>
    </ul>

**Comment by kevinparkerson** [comment]
Hi @dcoghill-salesforce. Thanks for the compliment! Here is a js fiddle of your code without the `ul` and `li` tags: https://jsfiddle.net/ss0cc1fe/2/   It works in both Chrome and Firefox. I'm guessing the behavior issue has more to do with the placard being inside a jQuery sortable (as it appears you are using here) vs the placard itself. Perhaps the sortable is preventing the click event from bubbling?

**Comment by dcoghill-salesforce** [comment]
Thanks @kevinparkerson, you were exactly right. 

There was a .disableSelection() call elsewhere in the code, which seems to have different effects in Firefox and Chrome. Thanks for your prompt follow-up!
