### ISSUE TITLE
Wrong Event Name in Wizard

### ISSUE THREAD

**Issue by waleedmazhar** [ExactTarget/fuelux#1417]
Event mentioned in documentation is **changed.fu.wizard**

Event actually fired is **change.fu.wizard**

**Comment by waleedmazhar** [comment]
at here http://getfuelux.com/javascript.html#wizard

**Comment by mbeard** [comment]
It should be `changed.fu.wizard`, as shown [here](https://github.com/ExactTarget/fuelux/blob/master/js/wizard.js#L252).  Are you using the latest version, or could you provide a code snippet to demonstrate.

**Comment by swilliamset** [comment]
@waleedmazhar thanks for the feedback

we have resolved this in [3.10.0](https://github.com/ExactTarget/fuelux/releases/tag/3.10.0). I have confirmed getfulux.com is also updated to 3.10.0. The issue will be closed but please reach out to us if you have any additional questions.

https://github.com/ExactTarget/fuelux/commit/0472d588c3dd6536efca00c5f59f17c00c84e24d#diff-dc5bd735259453d910d4cb0273c6c224R3474
