### ISSUE TITLE
Repeater paging counts for empty data set

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1420]
The pattern has been adjusted and needs to be update
<img width="591" alt="screen shot 2015-07-24 at 2 46 33 pm" src="https://cloud.githubusercontent.com/assets/347227/8882207/3a9f95a0-3213-11e5-88f9-de420629f409.png">

**Comment by BenjaminNeilDavis** [comment]
It appears to already have been fixed. This is what I am getting with current release. Page is 0 and the dropdown is also disabled

![image](https://cloud.githubusercontent.com/assets/6981338/8882978/672d22d0-3219-11e5-9897-c511183c41da.png)

**Comment by swilliamset** [comment]
the paging controls should be disabled when empty.

**Comment by swilliamset** [comment]
The "0" count should be removed to be 100% in sync with pattern.

**Comment by BenjaminNeilDavis** [comment]
Ok @interactivellama worked on a similar issue #1366. I can disable the items per page dropdown but appears @interactivellama has spoken to @jamin-hall about the 0 of 0
