### ISSUE TITLE
Tree: Add 'discloseUntil' or similar functionality

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux#1427]
We often have a requirement to reselect an item in a tree that could be many sub-folders deep. It would be nice to be able to call a single function with the item's id and have the tree open all of the parent folders and re-select the item.

The first version of this could continually open folders until it finds the selected ID. But it would be preferable if all of the folders that were opened, but do not contain the selected ID, were closed.

There are some cases where we are able to store all of the parent folder IDs, adding support for those could streamline the opening of all of the parent folders, but having to the option to discloseUntil without the parent IDs would still be valuable.

**Comment by ashl1** [comment]
The interesting moment is to select hasn't loaded item with ```discloseUntil()```. The way to do it strongly depend on ```datasource``` function implementation. I suggest to use different ```expandedDatasource``` for that purpose. That function should return the array of all levels lists (started from specified ```initialItem```, by default ```null```) required to disclose to specified ```item```.
What do you think it about?
