### ISSUE TITLE
Having problem while using FuelUX scheduler in angularJS

### ISSUE THREAD

**Issue by Xainu31** [ExactTarget/fuelux#1429]
I am trying to use FuelUX scheduler control in my angular application. But i am not even able to create the control on the first place.
I have written this code in my controller 

$('#myscheduler').scheduler();

And in my html i have written this 

``` html
<div class="form-horizontal container-fluid scheduler" 
        data-initialize="scheduler" 
        role="form" 
        id="myScheduler">
</div>
```

But nothing is happening

**Comment by vernak2539** [comment]
Could you post a fiddle of the problem?

**Comment by Xainu31** [comment]
Here is the fiddle
https://jsfiddle.net/h1nxusx1/

**Comment by vernak2539** [comment]
So it looks as if you haven't included the markup. Here's an [update of the fiddle](https://jsfiddle.net/h1nxusx1/1/) with a working solution. 

So you'll need to include the markup ([example](https://github.com/ExactTarget/fuelux/blob/master/markup/scheduler.html)) where ever you want to use it. 

In angular, I would suggest creating a directive with this markup in a template file, then transclude the template into where you're using your directive. This would also help you isolate and use the jquery events that the scheduler will throw ($scope.$apply).

Let me know if there's anything else

**Comment by vernak2539** [comment]
The scheduler mark-up is a lot and I wish in this case we would be able to dynamically create it, but since that's not the stance on Bootstrap, it's not the stance on FuelUX

**Comment by Xainu31** [comment]
Ohk thanks for the help.. But i need the markup for

http://getfuelux.com/javascript.html#scheduler-examples

This example and couldn't find it any where

**Comment by vernak2539** [comment]
I believe that is in the markup provided, but it seems that it is never shown correctly. That example looks wrong as well, in the fact that re-occurrence stuff should only be showing if certain repeatable values are selected. @kevinparkerson may be able to take a look

**Comment by interactivellama** [comment]
The first example shown in the documentation is for showing all the options, but one would never want the user to interact with it that way. 

The second example, "Live Demo," should be using the markup from http://getfuelux.com/javascript.html#scheduler-usage-markup.

**Comment by vernak2539** [comment]
@interactivellama I'm not sure this merits a close with that explanation. In my prior comment, I created the proper fiddle and it still didn't work. I have a feeling it's due to the angular/jquery combo or the way it's initialized

**Comment by cormacmccarthy** [comment]
We will be addressing this in an upcoming release. Thank you!
