### ISSUE TITLE
How to change default pageSize of repeater

### ISSUE THREAD

**Issue by kdon80** [ExactTarget/fuelux#1430]
How to change default pageSize of repeater?
I tried the following by "dataSourceOptions:{pageSize:50}," but didn't work. Help would be greatly appreciated.

Thanks,

.repeater({  
        		dataSource: DataSource,
        		defaultView: 'thumbnail',
        		staticHeight: false,
        		dataSourceOptions:{pageSize:50},

**Comment by mbeard** [comment]
There is declarative way to accomplish this as well.  Ensure the list item corresponding to the desired default page size includes the `data-selected` attribute.  This will select that page size by default in the repeater and ensure that option passed to the data source.

```<ul class="dropdown-menu" role="menu">
     <li data-value="10"><a href="#">10</a></li>
     <li data-value="25" data-selected="true"><a href="#">25</a></li>
     <li data-value="50"><a href="#">50</a></li>
</ul>```

**Comment by kdon80** [comment]
Thanks a bunch! That worked perfectly!
