### ISSUE TITLE
FuelUX wizard selectedItem method buggy

### ISSUE THREAD

**Issue by vojtmen** [ExactTarget/fuelux#1441]
There is difference between:

                $('#BLA').wizard('selectedItem', {
                    step : "5"
                });

                $('#BLA').wizard('selectedItem', {
                    step : 5
                });

when 5 is the last step - when you pass "5" string it does not change the button for the last step (e.g. from Next to Submit) while passing integer value does.

**Comment by swilliamset** [comment]
# Notes for assignee
Using `===` is causing this problem. The `step` attribute could be coerced to make the method more friendly.
https://github.com/ExactTarget/fuelux/blob/master/js/wizard.js#L168

@vojtmen thanks for the find. PR's are also greatly appreciated.

**Comment by interactivellama** [comment]
Are we sure we want to coerce the type? Right now, `"5"` will look for a `"5"` as a `"data-name"` or label, I believe. If it's a number, it's assumed to be an index.

http://getfuelux.com/javascript.html#wizard-usage-methods-selectedItem
