### ISSUE TITLE
Scheduler not RFC 2445 compliant - weekly repetition 

### ISSUE THREAD

**Issue by nglessner** [ExactTarget/fuelux#1450]
The scheduler is producing a RRule that is not RFC 2445 compliant when using a weekly repetition with more than one day. Using the example: Weekly on Tuesday and Thursday for 5 weeks: the RRULE generated would be: FREQ=WEEKLY;COUNT=5;WKST=SU;BYDAY=TU,TH;

From the RFC document: https://tools.ietf.org/html/rfc2445 it should be:
DTSTART;TZID=US-Eastern:19970902T090000 RRULE:FREQ=WEEKLY;COUNT=10;WKST=SU;BYDAY=TU,TH
==> (1997 9:00 AM EDT)September 2,4,9,11,16,18,23,25,30;October 2

The difference is the COUNT parameter. There's also a unsupported trailing semicolon that some RFC 2445 parsers will have trouble with.

**Comment by interactivellama** [comment]
Thank you for finding this issue.

The trailing comma should be fixed by #1371 added in release 3.10.0. What version are you using?

**Comment by nglessner** [comment]
I'm just using the current nuget package which seems to be 3.6.3

**Comment by interactivellama** [comment]
If this is true, iCal seems to have implemented it wrong.

<img width="247" alt="screen shot 2015-08-12 at 11 14 02 am" src="https://cloud.githubusercontent.com/assets/1290832/9227787/4c2558b2-40e3-11e5-84b7-ac56a2316c3b.png">

Produces this: `RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1;BYDAY=MO,TU,WE;WKST=SU`

**Comment by interactivellama** [comment]
Example from Google:

![screen shot 2015-08-17 at 1 47 47 pm](https://cloud.githubusercontent.com/assets/1290832/9311784/ad3175f8-44e6-11e5-8f13-6d379688d6c7.png)


Generates the following:
`RRULE:FREQ=WEEKLY;COUNT=4;BYDAY=TU,WE`

The "Repeat on" label is the key I think. Our's does not use "on".

**Comment by interactivellama** [comment]
@nglessner In our scheduler, "occurrence" is the same as `count` or "times" and does not correspond to the number of weeks or the repetition pattern. I believe this is confusing, but does align to how Google and Apple have implemented it.

**Comment by nglessner** [comment]
![image](https://cloud.githubusercontent.com/assets/11987939/9312746/59b6a13e-44e4-11e5-9829-01bf95f4bb78.png)

You are correct! I'm surprised by this and I agree. I wouldn't call this UI intuitive, but it's probably best to follow the rest of the industry. Users will have to do math to determine the number of occurrences if they want to do multiple times per weeks for so many weeks.
