### ISSUE TITLE
Add nuget support for our Windows/ Visual studio friends

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1452]
All the maintainers are Mac folks, but if there's enough demand for this, we could implement with grunt-nuget.

**Comment by swilliamset** [comment]
lets wait until we have some feedback from the community. we can sure the issue on twitter etc.

**Comment by pweb23** [comment]
I would certainly appreciate a nuget package! Our company uses nuget quite a bit, and are looking at adding fuelux to a new project.  Thanks for all the hard work

**Comment by interactivellama** [comment]
@pweb23 If you'll provide the config file, I will add it in for releases.
