### ISSUE TITLE
Placard respect form element classes.

### ISSUE THREAD

**Issue by jbarngr** [ExactTarget/fuelux#1459]
When apply 'has-error' to the placard, styling is overriding. 
![screen shot 2015-08-11 at 8 58 53 pm](https://cloud.githubusercontent.com/assets/915237/9214458/e99518da-406b-11e5-95a3-28d46a7bb421.png)

**Comment by chriscorwin** [comment]
I have done work on this, but need feedback from @jamin-hall and @rachelprice (who doesn't seem to be in this project, weird, maybe @swilliamset can invite her?)... 

Anyway, I can see two ways of doing this, and wish to know which to pursue:

![placard-all-error](https://cloud.githubusercontent.com/assets/362417/9228058/aba7a226-40e4-11e5-9ebc-2130590188d6.png)

![placard-only-input-error](https://cloud.githubusercontent.com/assets/362417/9228057/ab8aa356-40e4-11e5-9d71-92032537536e.png)


i can see arguments for both ways.

On the one hand, in bootstrap, error state being applied to a thing (in this case `.placard`) tends to style _the entire thing_, not just the one element within it that is the _cause_ of the error.

On the other hand, it’s fugly as ayche ee double hockey sticks to make the whole damn placard show error.

Another thought: just using the color red to indicate error state is distasteful bordering on user-hostile. 

Anyway, i’ve pushed my WIP so far, but will await feedback before either issuing a pull request or modifying it.

**Comment by chriscorwin** [comment]
@jamin-hall just assign this back to me when you've reached a conclusion and or have decided you will leave it up to me.

¯\_(ツ)_/¯

**Comment by swilliamset** [comment]
According to @jamin-hall this is in @chriscorwin's hands as he checks with @jbarngr on this proposed solution

![pasted_image_at_2015_08_18_01_45_pm](https://cloud.githubusercontent.com/assets/347227/9338331/31f8220c-45b2-11e5-8a28-022620f00d65.png)

**Comment by swilliamset** [comment]
upon further research this item can be considered an enhancement and should be visited when syncing with future validation efforts
