### ISSUE TITLE
Change event firing on init

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1462]
The repeat frequency changes itself to `"1"` on first date selection if initially set to `"0"` (which is a feature of the scheduler). This causes the change event to be fired on first date selection.

Steps to reproduce:
1. Go to http://getfuelux.com/javascript.html#scheduler
2. Open console and set breakpoint on line 6740 of fuelux.js
3. Scroll down to "static example" (in grey well with all options visible)
4. Change the selected date

Expected result:
Breakpoint fires only once with new date.

Actual result:
Breakpoint fires twice. First with new date, and then with repeat value (which was initially `"0"`, but has now been set to `"1"`)

**Comment by cormacmccarthy** [comment]
This is causing problems in Backbone, because I have bound my view to fire a `.set` on the model whenever the scheduler fires a `changed` event. Since the value isn't actually changing, a `set` gets fired on the Backbone model which doesn't change anything and makes the `hasChanged()` value begin returning `false` instead of `true`.

So, `Backbone.model.set('startDateTime', newDateTime)` gets called, and calling `hasChanged()` returns `true`. But, immediately an errant `Backbone.model.set('recurrencePattern' newRecurrence)` gets called, and since nothing changes during that `set` then calling `hasChanged()` now inappropriately returns `false`.

**Comment by cormacmccarthy** [comment]
Here's a work around if anyone else has the same problem:

```
        events: {
            'changed.fu.scheduler @ui.scheduler': 'updateModel'
        }
        , setScheduleModel: function setScheduleModel () {
            var schedulerValues = this.ui.scheduler.scheduler('value');

            var supposedlyNewData = {
                iCalRecur: schedulerValues.recurrencePattern
                , startDate: schedulerValues.startDateTime
                , timeZoneId: schedulerValues.timeZone.name
            };

            var currentData = {
                iCalRecur: this.model.get('iCalRecur')
                , startDate: this.model.get('startDate')
                , timeZoneId: this.model.get('timeZoneId')
            }

            if(!_.isEqual(currentData, supposedlyNewData)){
                this.model.set(supposedlyNewData);
            }
        }
```

**Comment by interactivellama** [comment]
Could this be the Spinbox firing two events at initialization bug? Similar to https://github.com/ExactTarget/fuelux/issues/522

**Comment by swilliamset** [comment]
https://github.com/ExactTarget/fuelux/blob/master/js/scheduler.js#L77-L82

**Comment by swilliamset** [comment]
removing 'high priority'. still needs solution but no applications are waiting on it.

**Comment by swilliamset** [comment]
looking here next https://github.com/ExactTarget/fuelux/blob/master/js/scheduler.js#L103-L104

**Comment by interactivellama** [comment]
Datepicker and scheduler need to be synced with each other after #1440.
