### ISSUE TITLE
Return time zone ID with name and offset

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1466]
http://getfuelux.com/javascript.html#scheduler-usage-methods-value

Need third property to return of `id` (or something) which would represent the id of the value the user  chose. For instance, if you called `$('#myScheduler').scheduler('value');` after the user chose "(GMT) Casablanca *" it would return the following timezone object:

```
timeZone: {
    offset: '+02:00',
    id: '2'
    name: "(GMT) Casablanca *"
}
```

Our APIs require us to pass them the `id` rather than the offset or the name.

**Comment by interactivellama** [comment]
Should this be hard-coded or would you like it as an init option?

Can you provide a JSON map of the offsets to to ids? I have no idea why the dropdown list is in the order it is in.

```
timeZoneId: {
    '+02:00':  '2'
}
```

**Comment by cormacmccarthy** [comment]
Already issued PR.

Basically what I need is just for timezone to return all data values of the timezone selectlist instead of just offset and name. So, with this change we actually have less code, less complexity, and more flexibility.
