### ISSUE TITLE
Scheduler's misspelling of occurrence

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1467]
Replace "occurance" with "occurrence." This misspelling was introduced in the 3.0.0 release and has been present since May 2014 in the codebase. It was spelled correctly in 2.x.

@jamin-hall Maybe we should change it to `time(s)`, in order to more easily catch where it needs to be updated. There are about 25 uses of the misspelling across the apps we have internally from what I can tell.

**Comment by cormacmccarthy** [comment]
don't forget "reccurance" with "recurrence".

**Comment by interactivellama** [comment]
Just for reference:
> Something that recurs happens repeatedly, perhaps at regular intervals. Something that reoccurs happens again, but not necessarily repeatedly or at regular intervals. For example, the sunrise recurs, and an unpredictable event that happens to occur more than once—such as an earthquake or a financial crisis—reoccurs.

http://grammarist.com/usage/recur-reoccur/
