### ISSUE TITLE
Add copy markup button in documentation

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1477]
To prevent long drag and copy for scheduler and repeater.

**Comment by swilliamset** [comment]
I'm so close! This works relatively well except it doesn't retain whitespace.

```
$('code').each(function() {
	var code = $(this).text();
    $(this).parent()
        .css('position', 'relative')
        .append(
            $('<div style="position: absolute; top: 0; left: 0;">super copy</div>')
                .click(function() {
                    window.prompt("Copy to clipboard: Ctrl+C, Enter", code);
                })
        );
});
```

**Comment by cormacmccarthy** [comment]
Guys, I'd love to see Codepen & JSFiddle links for each example in the docs. Requiring users to figure out our source code for this entire file is a bad experience.

Perhaps we could figure out some way to separate all of the code (JS, CSS & HTML) for each of the examples into separate files which we utilize both for the docs and for feeding into JS Fiddles or Codepens or something. Even gists would be better than what we have.
