### ISSUE TITLE
Keep end date from being before start date

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1487]
1. Go to http://getfuelux.com/javascript.html#scheduler-examples-live-demo
2. Select a future start date
3. Select a repeat (e.g. hourly)
4. Select end on date

Expected results:
End on date sets itself to just after the first possible run (so, weekly repeat, the end on date would set itself to start date + 1 week. Hourly repeat, end on date would set itself to start date + 1 hour)

Actual results:
End on date sets itself to current date (which is prior to start date)

![image](https://cloud.githubusercontent.com/assets/8006971/9475068/506e2ddc-4b32-11e5-94b5-dffecf489f48.png)

Any time the user changes the start date, if it is greater than the end date, we need to adjust the end date by the repeat increment.

**Comment by interactivellama** [comment]
How does this validate? We probably don't want to change the UI. 

Should we just supply an error event like `invalidStartAndEnd`?

**Comment by interactivellama** [comment]
One option would be to re-init the datepicker when on date is selected with restricted dates before the start.
