### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prop' of undefined when check checkbox

### ISSUE THREAD

**Issue by renathy** [ExactTarget/fuelux#1488]
When I am trying to check checkbox with js, it fails. My markup is the following:

```html
<label class="checkbox-custom" data-initialize="checkbox">
                                        <input class="sr-only" type="checkbox" value="" data-bind="attr: {id: $data.Id}, checked: $data.IsSelected" id="1259d94d-2c0f-440c-b7a4-e2189d2bdae1">
                                        <span class="checkbox-label" data-bind="text: $data.Name">Austria</span>
                                    </label>
```

I have fuelux class added to html tag: 

<html class="fuelux">

I do not initialize checkboxes in any other specific way. Afterwards I try to call 

```javascript
$('#1259d94d-2c0f-440c-b7a4-e2189d2bdae1').checkbox('check'); 
```

and it fails.

Uncaught TypeError: Cannot read property 'prop' of undefined

**Comment by cormacmccarthy** [comment]
http://getfuelux.com/javascript.html#checkbox

Please put the ID on the label.
