### ISSUE TITLE
Make step increment work properly in scheduler

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1491]
When limiting step increments, need to keep combobox from allowing increments outside of that to be entered or set.

Right now if the step increment is "5", scheduler repeat starts at "1" (to avoid starting at "0" since "that doesn't make sense") and then goes in increments of 5 from there (6, 11, 16...) and also allows other increments to be manually entered. It should, instead, start at 5 (instead of 1) and only allow increments of 5.

**Comment by futuremint** [comment]
Taking notes: there are two bugs here.
1. The scheduler sets the spinbox to "1" without respecting the spinbox's increment.
2. The spinbox should restrict input only to positive multiples of its increment while in the scheduler.
