### ISSUE TITLE
Need Tree dropdown (tree + combobox) control

### ISSUE THREAD

**Issue by ashl1** [ExactTarget/fuelux#1496]
I need the control to dropdown tree and show the selected item in the field
From where I can start from?

**Comment by cormacmccarthy** [comment]
There is a new (somewhat experimental, and therefore undocumented) feature called the "picker" that will allow you to do this.

https://github.com/ExactTarget/fuelux/blob/master/js/picker.js


You can see an example of how to use it in our [index.html](https://github.com/ExactTarget/fuelux/blob/master/index.html#L2440) and [index.js](https://github.com/ExactTarget/fuelux/blob/master/index.js#L1231) files.
