### ISSUE TITLE
Tree control fires selected.fu.tree while open folder

### ISSUE THREAD

**Issue by ashl1** [ExactTarget/fuelux#1497]
The Tree control doesn't differ 'open folder' and 'select folder' actions while 'folderSelect' is true. When click on right arrow to expand the folder it will be selected and produces 'selected.fu.tree' event.
I assume that these actions should differs. The expanding by clicking on right arrow and selecting by clicking on item itself.

**Comment by cormacmccarthy** [comment]
I can't reproduce this. It is differentiating them for me. Are you using the latest version of Fuel UX? Can you provide a JS Fiddle or something please?
