### ISSUE TITLE
Apply Ellipsis to input boxes as well as textareas

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1502]
The documentation states that input boxes on placards can have ellipsis applied to them if they are too long, but our code does not support this.

**Comment by merong12** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

merongmall@naver.com 님께 보내신 메일 <Re: [fuelux] Apply Ellipsis to input boxes as well as textareas (#1502)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
