### ISSUE TITLE
Detect step number event

### ISSUE THREAD

**Issue by Ottiko** [ExactTarget/fuelux#1503]
Can you tell me how I can detect step number event (step number and direction) when click at this button [steps](http://i.imgur.com/ILrYBsv.png)

I need this, becouse I have same custom code to **.on('actionclicked.fu.wizard', function(e, data) {...}**

I try to kill event **$('body').on('click', 'ul.steps li', function(e) { return false; });** but did'n work...

**Comment by cormacmccarthy** [comment]
http://getfuelux.com/javascript.html#wizard-usage-events

Please refer to our documentation. Use event.preventDefault() to cancel the event.
