### ISSUE TITLE
Pillbox issue

### ISSUE THREAD

**Issue by sanaalauddin** [ExactTarget/fuelux#1507]
I am using the Pillbox but it isnt working(the words not going into a box after a comma). Im assuming the jQuery is not loaded. Can someone please guide me as to which javascript file needs to be included in the form? I have tried several versions of jquery.js but nothing seems to be working. Thanks

**Comment by interactivellama** [comment]
Please follow http://getfuelux.com/getting-started.html#templates suggestions when requesting external files.

We recommend Javascript files being requested at the end of the page.
