### ISSUE TITLE
Arrow alignment off for down arrow

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1508]
![image](https://cloud.githubusercontent.com/assets/8006971/9793595/228d1d7c-57b4-11e5-88e8-073faf04b589.png)

**Comment by merong12** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

merongmall@naver.com 님께 보내신 메일 <Re: [fuelux] Arrow alignment off for down arrow (#1508)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
