### ISSUE TITLE
InfiniteScroll on a repeater.

### ISSUE THREAD

**Issue by gdborton** [ExactTarget/fuelux#1516]
Documentation seems to be inaccurate.

http://getfuelux.com/javascript.html#repeater-usage-methods-infinite-scrolling

The snippet indicates a single argument for the `infiniteScrolling` function, while the function actually takes 2, a boolean and an options hash.

```javascript
$('#myRepeater').repeater('infiniteScrolling', {enable: true});
```

It also doesn't seem to make the repeater scroll infinitely... just hides parts of the ui.  I could be doing something wrong, but I couldn't find an example of using infinite scroll with a repeater.

**Comment by cormacmccarthy** [comment]
The options hash is optional.

**Comment by cormacmccarthy** [comment]
There is an example of using infinite scroll with a cardview repeater in the https://github.com/ExactTarget/fuelux/blob/master/index.js#L644 file.

**Comment by gdborton** [comment]
@cormacmccarthy yes, but the actual call should look like this.

```javascript
$('#myRepeater').repeater('infinitescrolling', true, {hybrid: true});
```

**Comment by cormacmccarthy** [comment]
Thanks @gdborton
