### ISSUE TITLE
Repeater displaying incorrectly when on a wizard pane

### ISSUE THREAD

**Issue by marvinpribble** [ExactTarget/fuelux#1517]
I have a wizard with 3 steps and one or two grids on each step. When I click on a step and the grid on that pane is displayed, the headings are wonky and the static height for the grid is not honored. If I resize the window, the headings appear correctly and the grid resizes to the static height.

Short term solution was to call resize on wizard step change:
$('.repeater').repeater('resize');

**Comment by cormacmccarthy** [comment]
I wonder if this has to do with the repeater not being visible when you init it.
