### ISSUE TITLE
Emptying of the datepicker value not possible

### ISSUE THREAD

**Issue by vojtmen** [ExactTarget/fuelux#1519]
Once date is selected in the datepicker, there is no possibility to clean this value. One can only delete the string via keyboard + clicking with the mouse outside the popped up datepicker, but then it won't trigger change listeners.

**Comment by cormacmccarthy** [comment]
Right now changed only fires for successful `Date` changes through textual input (not clicks!). Setting to `null` is not successfully changing a `Date`, but is rather merely changing the value shown in the input box.

		inputChanged: function () {
			var inputVal = this.$input.val();
			var date;
			if (inputVal !== this.inputValue) {
				date = this.setDate(inputVal);
				if (date === null) {
					this.$element.trigger('inputParsingFailed.fu.datepicker', inputVal);
				} else if (date === false) {
					this.$element.trigger('inputRestrictedDate.fu.datepicker', date);
				} else {
					this.$element.trigger('changed.fu.datepicker', date);
				}

			}
		}



If you truly want to listen to all change events on the input box, you should instead listen like this:

`$('#myDatepicker').on('change dateClicked.fu.datepicker', function(){ console.log('changed!'); });`
