### ISSUE TITLE
Not working Meteor package in Atmosphere

### ISSUE THREAD

**Issue by medihack** [ExactTarget/fuelux#1521]
It seems there is a not working (official?!) Meteor package of fuelux in Atmosphere (the Meteor package registry): https://atmospherejs.com/exacttarget/fuelux

After adding the package to my Meteor app nothing from fuelux is available in the app. It even seems that the package does not contain any CSS files.

**Comment by cormacmccarthy** [comment]
I'm skeptical that this is "official". We are looking into it. Thanks!

**Comment by medihack** [comment]
Ok, is uses the ExactTarget namespace. That way it appears as it would be official. May I create a pull request with a working package.js for Meteor (pretty straight forward) and we contact the atmosphere guys that it will be replaced with an official version?

**Comment by futuremint** [comment]
@medihack I checked the metadata of that Atmosphere package and whoever created it has it currently pegged to Fuel UX version 3.7.1.  So even if we merge your Pull Request it won't fix this issue until whoever created that un-official package on Atmosphere updates it.

I don't see any information in Atmosphere about who created it... is there a way to do that?
