### ISSUE TITLE
Repeater action list won't show if no data initially

### ISSUE THREAD

**Issue by braigo64** [ExactTarget/fuelux#1522]
If there is no data in the repeater when it is initialized, the list action column (and checkbox column too) won't show which is fine.  However, if the repeater gets populated with data later, the list action column will never show up.

The checks done in renderThead() of repeater-list.js make too many assumptions.  In order to work around this issue I had to make a change to my implementation and a change to the repeater-list.js code.

In order to pass the checks, I set my columns to an empty array in the data source function when there is no data.  This way when the data does load it will pass the differentColumns() check.

Then line 791 needed to change from:

``` javascript
    if (data.count < 1) {
        this.list_noItems = true;
    }
```

to:

``` javascript
    this.list_noItems = data.count < 1;
```

Otherwise, it always thinks there is no data when there actually is data.

Simply changing the line in repeater-list.js isn't enough because the first time check, different columns check, and thead length check will never pass unless the end user is aware that they need to alter their column list to work around the checks.  Therefore, I think there is a better way to determine whether the list action column should be rendered or not.

**Comment by futuremint** [comment]
@braigo64 we welcome Pull Requests and help from our users.  Looks like you already have an idea how to fix it... perhaps you could contribute by sending us how you think it could be fixed in a Pull Request?  Here is some help on how to contribute: https://github.com/ExactTarget/fuelux/wiki/Contributing-to-Fuel-UX
