### ISSUE TITLE
Bootstrap 4 planning

### ISSUE THREAD

**Issue by troymccabe** [ExactTarget/fuelux#1540]
Any thought around the alphas of BS4? I'd be more than happy to start digging in to check stuff out / start a bs4-compatible branch, but wanted to make sure I'm not doing work you guys have already started

**Comment by TheJaredWilcurt** [comment]
I am all for switching over to Sass:

![Preprocessor Pie Chart](https://cloud.githubusercontent.com/assets/4629794/10076840/89a87324-62ab-11e5-861e-cace7c14a19e.png)

**Comment by swilliamset** [comment]
We are currently reconsidering our dependency on Bootstrap.

Based on previous experience we feel moving towards a more independent library allowing for framework native implementation of controls would be more beneficial.

Stay tuned.

**Comment by troymccabe** [comment]
So something like bootstrapvalidator -> formvalidation did? Awesome!

I'll keep an eye out for updates--thanks!

**Comment by saad749** [comment]
Will you be supporting bs4?

**Comment by PaulScala** [comment]
+1 I would really like to see bootstrap 4 support.

**Comment by interactivellama** [comment]
There are no plans to support Bootstrap 4. Salesforce is not actively supporting Fuel UX anymore. Anyone is welcome to fork as long as they keep to the license.

**Comment by brouillon** [comment]
2018 up for this one !
A bootstrap 4 support will be planned ?

Thanks

**Comment by interactivellama** [comment]
I think the party has mostly moved over to https://react.lightningdesignsystem.com/

**Comment by brouillon** [comment]
Ok :(
Thanks for information
