### ISSUE TITLE
Dynamic edit steps

### ISSUE THREAD

**Issue by Ottiko** [ExactTarget/fuelux#1541]
For exp. I have steps:
**1 step - Name
2 step - Surname
3 step - Age
4 step - Country
5 step - Address**

2 ways for process, with "**4 step - Country**" step and without. If with all work good, but if without
I need to hide "**4 step - Country**" and change "**5 step - Address**" at "**4 step - Address**"

How I can do it...

**Comment by Ottiko** [comment]
???

**Comment by futuremint** [comment]
Are you talking about our Wizard control?  If so the steps are defined in the markup.

**Comment by Ottiko** [comment]
I hide step with **.hide();** and change last step number **$('#sometimes_change .badge').html('4');** I know it's a hardcode, but I didn't see any ideas...

**Comment by cormacmccarthy** [comment]
We will be addressing this in an upcoming release. Thank you!
