### ISSUE TITLE
Spinbox step

### ISSUE THREAD

**Issue by NMFES** [ExactTarget/fuelux#1546]
Example configuration: value = 10, min = 10, max = 22, step = 5

Current steps will be: 10 => 15 => 20 => 22 => 17 => 12 => 10

It's not correct because on return direction after 22 must be 20, then 15 ...

I'm fixed this in Spinbox core code:

    output: function (value, updateField) {
                //////////////////////////////////////////////////////////////////////
                if (value % this.options.step && value != this.options.max) {
                    value = value - (value % this.options.step) + this.options.step;
                }
                //////////////////////////////////////////////////////////////////////

                value = (value + '').split('.').join(this.options.decimalMark);
                updateField = (updateField || true);
                if (updateField) {
                    this.$input.val(value);
                }

                return value;
            },

**Comment by cormacmccarthy** [comment]
Good catch, thank you! This should be fixed in our 3.11.4 release.
