### ISSUE TITLE
spinbox initialization

### ISSUE THREAD

**Issue by guille50** [ExactTarget/fuelux#1549]
I'm getting an error after spinbox initialization through js:
"Uncaught TypeError: Cannot read property 'addEventListener' of undefined."

Actually i don't have any problem through html definition, however i need set a max val, but that just can be used by js definition.

http://plnkr.co/edit/03cqFkwSUu91ivzv7kG7?p=preview

**Comment by cormacmccarthy** [comment]
Please make sure you are using the correct markup: http://getfuelux.com/javascript.html#spinbox-usage-markup

There is a bug in spinbox also that will be resolved with the release of 3.11.4.

Thanks!
