### ISSUE TITLE
Form builder is not working 

### ISSUE THREAD

**Issue by kitkat14** [ExactTarget/fuelux#1564]
just drag something to it and try to change an attribute it will show in the console: 

"Uncaught TypeError: Cannot read property 'previousAttributes' of undefined"

**Comment by mackaboogie** [comment]
Is there any progress on this? I spent a good deal of time integrating this, doing the edits to output JSON, etc. and then realized the popovers did not save (doh!).

I receive the following error when hitting save in the popover...

TypeError: model is undefined
var prevId = this.modelId(model.previousAttributes());
backbone.js (line 1148, col 13)

Thanks!

**Comment by cormacmccarthy** [comment]
Hoping to get to it this week.

**Comment by mackaboogie** [comment]
Thanks so much! Please post a reply once you have an update.

**Comment by futuremint** [comment]
@mackaboogie @kitkat14 this has been fixed on the website and is now live.
