### ISSUE TITLE
Cannot see options for small dropdowns on Windows due to scrollbars

### ISSUE THREAD

**Issue by nmerchant** [ExactTarget/fuelux#1565]
https://jira.exacttarget.com:8443/browse/EVENTS-403

On WIndows machines, the scrollbar takes up enough space that in the case of a dropdown that is already very tiny (i.e. choosing a number from 1-31 for a month/day), the possible values cannot be seen.

I fixed this issue specifically in Journey Builder by setting a min-width on the dropdown: https://github.exacttarget.com/IMHDev/ixn/commit/f0856c5c6997b23e4c603c095c6d9dd7ee698a32

**Comment by swilliamset** [comment]
Thanks for the heads up. Using `min-width` is a valid solution which we should include in our documentation. We will also consider the influence of scroll bars when we get a chance to reconstruct the control.

**Comment by cormacmccarthy** [comment]
min-width is already set at 160px in Bootstrap. This is probably a marketing cloud theme issue.

https://github.com/twbs/bootstrap/blob/master/less/dropdowns.less#L38
