### ISSUE TITLE
Wizard infinite horizontal scrolling issue

### ISSUE THREAD

**Issue by sanaalauddin** [ExactTarget/fuelux#1566]
I am using Wizard by FuelUX. For some reason i see an infinite horizontal scroll. I tried looking through the CSS but couldnt find any place setting the width of the page. I have attached the screenshot. Please help. Thanks.
![screen shot 2015-10-10 at 11 56 03 pm](https://cloud.githubusercontent.com/assets/12517730/10414599/7e58393a-6faa-11e5-8cb7-7477cb200e4e.png)

**Comment by swilliamset** [comment]
Could you proved the markup? Can you reproduce in a codepen.io or jsbin.com?  Also please visit the stackoverflow community. There may be an answer there already.
