### ISSUE TITLE
checkboxes are not checked until mouse over checkbox (bound via knockout)

### ISSUE THREAD

**Issue by renathy** [ExactTarget/fuelux#1576]
I have the same issue described here: http://stackoverflow.com/questions/29400160/how-to-initialize-fuelux-checkbox-with-knockout-binding

I am using knockout.with fuelux. I have many checkboxes and all are bound with knockout. Base on  user clicks my knockout  model properties are filled correctly, but unfourtunately fuelux checkboxes doesn't work as desired - those are checked only when I mouse over checkbox.

**Comment by swilliamset** [comment]
see https://github.com/ExactTarget/fuelux/issues/1582#issuecomment-156474089
