### ISSUE TITLE
fuelux checkboxes doens't work with knocokut

### ISSUE THREAD

**Issue by renathy** [ExactTarget/fuelux#1582]
If you bind checkbox values using knockout binding, then this does not work with fuelux.
If you change property (IsSelected for checkbox) of knockout model then checkbox doesn't toggle. I believe this is FuelUX fault.

FIRST
For instance, in this code I am trying to change IsSelected property in knockout model (self.IsSelected(false) or self.IsSelected(true)) and this doesn't affect checkbox state.

```javascript
<span class="checkbox country-selector-chb">
                                            <label class="checkbox-custom" data-bind="attr: {id: $data.Id}, clickBubble: false">
                                                <input class="sr-only" type="checkbox" data-bind="checked: $data.IsSelected" />
                                                <span class="checkbox-label" data-bind="text: 'All ' + $data.Name()"></span>
                                            </label>
                                        </span>
```

SECOND
Another problem is when I add click even on label, then checkbox also doesn't toggle. clickHandler does nothing, it is empty javascript function inside knockout model. As a result, checkbox stated doesn't toggle also. By knockout documentation http://knockoutjs.com/documentation/click-binding.html click binding will "will prevent the click event from taking any default action." and "However, if you do want to let the default click action proceed, just return true from your click handler function.". Thus if I add "return true" inside clickHandler function, checkbox state is toggled, however, click event fires twice. This doesn't happend without FuelUx.

```javascript
<span class="checkbox country-selector-chb">
                                            <label class="checkbox-custom" data-bind="attr: {id: $data.Id}, click: $data.clickHandler; clickBubble: false">
                                                <input class="sr-only" type="checkbox" data-bind="checked: $data.IsSelected" />
                                                <span class="checkbox-label" data-bind="text: 'All ' + $data.Name()"></span>
                                            </label>
                                        </span>
```

**Comment by swilliamset** [comment]
@renathy thanks for the feedback. i hope you've been able to some of our tools with your knockout project. however it was not architected to work with knockout. if you have a solution for your scenario which would improve fuelux for the rest of the knockout community please fee free to provide a PR.

also keep an eye out for future updates. we may have support for a [more native](https://github.com/ExactTarget/fuelux/issues/1540#issuecomment-142992174) knockout fit in the future.
