### ISSUE TITLE
Does checkbox support indeterminate state?

### ISSUE THREAD

**Issue by bohawi** [ExactTarget/fuelux#1588]
Hi FuelUX,  I am in need of a checkbox with an indeterminate state.

I see some styling that looks like this was considered, but I am having trouble getting it to work in FuelUX 3 or Fuel Fusion.  Is this supported?

**Comment by interactivellama** [comment]
Yes and no. It is supported in the native `<input>` checkbox of MCtheme (included in Fusion), but not the JS control `checkbox`. This page show an example of them: http://fuelux-snippets.herokuapp.com/checkbox-list

**Comment by bohawi** [comment]
Thank you @interactivellama, that snippet did the trick.
