### ISSUE TITLE
Repeater has horizontal overflow and when scrolled borders are messed up

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1589]
![image](https://cloud.githubusercontent.com/assets/8006971/10791834/8a8ef892-7d60-11e5-9a09-ec10878e5344.png)

http://codepen.io/anon/pen/KdvJrP?editors=101

Reported by @dkilgore

**Comment by kevinparkerson** [comment]
I am currently working on a image to SVG conversion task for AS but will work on this immediately following
