### ISSUE TITLE
Tree how to remove selected items

### ISSUE THREAD

**Issue by LiuXiao617111** [ExactTarget/fuelux#1596]
Question : While select one item,how remove others selected ?  
If configure multiSelect  property , Can only select  one. If l want select another,it must unselect this,then select others.   l want something like radio button. how l can do it

**Comment by mbeard** [comment]
If `multiSelect:false` is set, you are correct, it should only allow one node to be selected at a time.  In other words, if a node is already selected and you select a different node, it will deselect the previously selected node and select the current node.  

Can you clarify what you mean by "...something like radio".  The behavior described above is similar to behavior for a radio button group.

**Comment by LiuXiao617111** [comment]
Thank you for your reply . I know what you mean.

**Comment by mbeard** [comment]
I'm going to close this for now then.

**Comment by LiuXiao617111** [comment]
Does it mean that you will add a radio attribute . 
Remarks : radio like <input type="radio" name="" value="" /> in html

**Comment by mbeard** [comment]
Ah, I see what you're asking for now.  Can you embed a hidden input that changes value based on the selected node value of the tree?  You should be able retrieve that data from the `selected.fu.tree` event.

**Comment by interactivellama** [comment]
Like tree, pillbox is another Fuel UX control that is not "form compatible" out of the box. @LiuXiao617111 Here is how you can use a pillbox for form submission or post to the server. You should do something similar but with `selected.fu.tree` as Matt said.

http://stackoverflow.com/questions/29628271/how-can-i-use-fuel-ux-pillbox-as-an-element-in-a-html-form/29630297?noredirect=1#comment47408009_29630297
