### ISSUE TITLE
Fuel UX Wizard Cache problem

### ISSUE THREAD

**Issue by vladanzivanovic** [ExactTarget/fuelux#1604]
Hi, I use this wizard for insert and edit data.
When I first open to add new data all input fields are empty, which is good, but if I open to edit data and   after edit close form  and then open to add new all fields are filled with previous data.
I doing reset on form, but only visible input field are reset.
I try to reset only first time when user click next button, but if click prev button and then click next again all old data are here.
I reset every step only first time because user may enter some new data thet can't be cleared if he goes step before.

Thanks

**Comment by interactivellama** [comment]
Our wizard only hides and shows it's content containers. We do not manipulate any of the content within them.

You could try clearing your form inputs when one of the buttons is clicked:
$('#myWizard').on('actionclicked.fu.wizard', function (evt, data) {
  // clear my inputs in the active step content container
});

See http://getfuelux.com/javascript.html#wizard-usage-events for more info.
