### ISSUE TITLE
Repeater with infinite scrolling does not respect "end:true" property in callback

### ISSUE THREAD

**Issue by dreitman-sf** [ExactTarget/fuelux#1605]
Going off the documentation here:
http://getfuelux.com/javascript.html#infinite-scroll

Once i retrieve the last page of data the callback is called with dataSource similar to this
``` js
{
    end: true,
    items: ['Array', 'of', 'last', 'items', 'to', 'display', 'in', 'repeater']
}
```

However the infinite repeater continues to make calls for additional data. At this point i have to leave the items array undefined otherwise i get the "No Data" text repeated in the grid. This unfortunately produces an exception inside the repeater code. Not calling the callback will leave the spinner in place as well.

The expected result was once i returned "end:true" I would no longer receive calls into dataSource.

Here is some sample code demonstrating this issue. If you turn on debugging you will see a console error once you try and scroll past the last page of data.

Sample Code:
https://gist.github.com/dreitman-sf/f6fc01828e0b5c266b3f

Sample Code in Action:
http://bl.ocks.org/dreitman-sf/raw/f6fc01828e0b5c266b3f/

**Comment by swilliamset** [comment]
Found it

https://github.com/ExactTarget/fuelux/blob/master/js/repeater.js#L596

Working on solution.

**Comment by swilliamset** [comment]
In the mean time the paging information is not being passed in your example.

I've updated [here](https://gist.github.com/swilliamset/2f0a8cee581cd42709aa)
