### ISSUE TITLE
Scheduler "live demo" sample code broken

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1607]
Copying and pasting the "live demo" example code chunk from the getfuelux.com documentation results in a non-working scheduler.

With the "live demo" (http://getfuelux.com/javascript.html#scheduler-examples-live-demo) code from the docs:
https://jsfiddle.net/cmcculloh/h6gfhwnk/

With the "markup" (http://getfuelux.com/javascript.html#scheduler-usage-markup) code from the docs (works):
https://jsfiddle.net/cmcculloh/31omqduv/

**Comment by interactivellama** [comment]
This is probably related to #1599 and #1511.

**Comment by swilliamset** [comment]
@chriscorwin  please confirm the "live demo" code matches the "markup" code

**Comment by chriscorwin** [comment]
@cmcculloh please tell me exactly what URL you are seeing this issue at.

We have a lot of "live demo" stuff. :D

**Comment by swilliamset** [comment]
http://getfuelux.com/javascript.html#scheduler-examples-live-demo

vs

http://getfuelux.com/javascript.html#scheduler-usage-markup

would have to confirm with @cormacmccarthy to determine where he got the code for the two fiddles :guitar:
