### ISSUE TITLE
Unable to click any tab even with fix

### ISSUE THREAD

**Issue by developerdu** [ExactTarget/fuelux#1608]
As suggested in https://github.com/ExactTarget/fuelux-mctheme/issues/175 I am trying to get this code to work ...

    var $wizard = $('#MyWizard').wizard();
    var wizard = $wizard.data('wizard');
    $wizard.off('click', 'li.complete');
    $wizard.on('click', 'li', $.proxy(wizard.stepclicked, wizard));

It doesn't work as "wizard" is set to undefined.

**Comment by swilliamset** [comment]
The wizard plugin object you are looking for can be found at `$wizard.data('fu.wizard')`

Let me know if this helps.

**Comment by developerdu** [comment]
No it doesn't seem to help unfortunately.

var wizard = $wizard.data('fu.wizard');

Still results in "wizard" being set to undefined.
