### ISSUE TITLE
Make placard support non-input/textarea this.$field elements

### ISSUE THREAD

**Issue by kevinparkerson** [ExactTarget/fuelux#1612]
The placard should be able to support general elements (content-editable and otherwise) as the `.placard-field`. This would allow more extensive content to be edited via a placard

**Comment by cormacmccarthy** [comment]
Isn't that the point of the picker?

@jamin-hall may be interested in weighing in on this as well.

**Comment by kevinparkerson** [comment]
No, different purpose for that, plus this is a nice feature to have in general.
