### ISSUE TITLE
Trigger a search by javascript in the repeater

### ISSUE THREAD

**Issue by vincenzoabete** [ExactTarget/fuelux#1613]
I would like to know if the issue #220 has been fixed and how would I include the fix in Fuel UX 2.x if that is the case. Thanks

**Comment by interactivellama** [comment]
@vincenzoabete #220 was moved to the v3.0 list of concerns two years ago. The 3.x datagrid, now called repeater, would use the input from the search field to run repeater's `render()` method. You can see it working in [the repeater documentation](http://getfuelux.com/javascript.html#repeater).

Fuel 2.x is deprecated and only has bugfix releases a few times a year. We would be open to a pull request on the 2.x branch though. I'm going to close this issue, but feel free to re-open the conversation if you have additional questions.
