### ISSUE TITLE
Checkbox not visible when using bootstrap

### ISSUE THREAD

**Issue by andreasba** [ExactTarget/fuelux#1622]
Good evening,

when using bootstrap 3.3.5/js/bootstrap.min.js/~.css and the current version of fuel ux () I encounter the strange problem that the fuel ux renders the checkbox invisible:

![screenshot](https://cloud.githubusercontent.com/assets/15323226/11305251/0c5e1c24-8fac-11e5-9632-d778acbf57e7.JPG)

This is because Fuel UX adds the following CSS:

![fuelcss](https://cloud.githubusercontent.com/assets/15323226/11305320/650fe974-8fac-11e5-9405-efacb9e0d032.JPG)

If i remove it with Firebug it looks like it should:

![withoutfuel](https://cloud.githubusercontent.com/assets/15323226/11305357/90babbd0-8fac-11e5-8585-72986a6a8692.JPG)

My Laravel application is generating the following HTML Code

```html
                     <div class="col-md-12 checkbox">
                            <label data-initialize="checkbox">
                                <input data-initialize="checkbox" id="agb_checkbox" name="agb_checkbox" type="checkbox">
                                Ich stimme den <a href="#">AGB</a> sowie den <a href="#">Datenschutzbestimmungen</a> zu und nehme die <a href="#">Widerrufsbelehrung</a> zur Kenntniss.
                            </label>
                        </div>
```

It might be possible that I am doing something wrong with bootstrap since I am new to it, so your help is highly appreciated (or it might be a bug?)

Thanks
Andreas

**Comment by interactivellama** [comment]
`"checkbox-custom checkbox-inline` appear to be missing. This is the code for an inline checkbox:
```
<label class="checkbox-custom checkbox-inline" data-initialize="checkbox"  id="myCheckbox5">
  <input class="sr-only" type="checkbox" value="option1"> <span class="checkbox-label">1</span>
</label>
```
http://getfuelux.com/javascript.html#checkbox-examples-inline

Feel free to reopen if that doesn't fix it.
