### ISSUE TITLE
Pillbox with dropdown should allow distinction between pillbox and dropdown text

### ISSUE THREAD

**Issue by alexweissman** [ExactTarget/fuelux#1680]
The pillbox widget can take a [callback with a list of items that will appear in a dropdown](http://getfuelux.com/javascript.html#pillbox-usage-options) when the user starts typing.  When an item from the dropdown is selected, the `text` for that item becomes the `text` of the pillbox.

However, there are many cases where we would want to display extended information in the dropdown, but not in the pillbox.  I propose an additional attribute for dropdown items, `label`, which will supersede the `text` for display purposes in the pillbox.

For example, I might declare my dropdown items as:

```
[
    {
        text  : "Some long description or HTML",
        value : "0",
        label : "Item0"
    },
    {
        text  : "Another long, nicely formatted description here",
        value : "1",
        label : "Item1"
    }
]
```

The dropdown would display the `text` fields for these items, but when an item is actually selected, only `label` would be displayed in the pillbox.
```

**Comment by futuremint** [comment]
Great idea!  Send us a Pull Request and we'll review it (and I'll re-open this ticket if you want to work on a fix).
