### ISSUE TITLE
Thumbnail repeater extension does not return selected items' data

### ISSUE THREAD

**Issue by nmerchant** [ExactTarget/fuelux#1686]
The repeater list extension returns data as expected, as an object containing the selected item's element as well as the item's data object.

The repeater thumbnail extension, however, only returns the item's element.

**Comment by nmerchant** [comment]
https://github.com/ExactTarget/fuelux/pull/1685

**Comment by swilliamset** [comment]
see https://github.com/ExactTarget/fuelux/pull/1685#issuecomment-175115377 for "enhancement" label removal
