### ISSUE TITLE
Sort columnA by columnB functionality

### ISSUE THREAD

**Issue by michaeldevenney** [ExactTarget/fuelux#1700]
Is there a way to sort by a column that isn't shown in the reapeater but does exist on the datasource?  I know I can do it programmatically, but if there is (or could be) a way to set this up in the Column definition that'd be cool.  My use case is a date field that has a specific display (user requirement) that doesn't lend itself well to sorting.  I include the actual date in the datasource, but don't see a way to wire it up to use the date property when sorting.  

Maybe adding something like a sortBy property in the column definition?  The last two columns are the dates that I'm referring to.
 var columns = [
       { 'label': "Credential", 'property': "Credential", 'sortable': true },
       { 'label': "Candidate", 'property': "Candidate", 'sortable': true },
       { 'label': "Reference Number", 'property': "ReferenceNumber", 'sortable': true },
       { 'label': "Status", 'property': "Status", 'sortable': true },
       { 'label': "Received", 'property': "ReceivedDisp", 'sortable': true', sortBy': "ReceivedDate"  },
       { 'label': "Available Until", 'property': "AvailableUntilDisp", 'sortable': true, sortBy': "AvailableDate"  }
        ];

**Comment by futuremint** [comment]
The recommended way at this time is to handle this programmatically in your application.  Thanks!
