### ISSUE TITLE
expose onkeyup in combobox for typeahead support

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1710]
maybe use search input which has [onkeyup support](https://github.com/ExactTarget/fuelux/blob/master/js/search.js#L38-L40)

add documentation and example

**Comment by cormacmccarthy** [comment]
Typeahead. Basically a combobox that onkeypress filters options down to matching results, or if no matches are found displays some sort of error.

Still some debate around whether we should create a new component, or use combobox and create some sort of extension, and how much of this we should implement for the end user (do we add a datasource or not)

Search has a somewhat similar behavior that fires events on keypress if a certain option is provided: 
https://github.com/ExactTarget/fuelux/blob/master/js/search.js#L38-L40
