### ISSUE TITLE
Scheduler doesn't work with default Hash

### ISSUE THREAD

**Issue by wlodi83** [ExactTarget/fuelux#1711]
Hi,

I save scheduler Javascript JSON object as a String in my database:

`"{\"startDateTime\":\"2016-02-08T00:00Z\",\"timeZone\":{\"text\":\"(GMT) Monrovia, Reykjavik\",\"selected\":true,\"offset\":\"+00:00\",\"name\":\"Greenwich Standard Time\"},\"recurrencePattern\":\"FREQ=MINUTELY;INTERVAL=1;UNTIL=20160211\"}" `

I convert that string into Hash object using Ruby:

`JSON.parse(scheduler_string, symbolize_names: true)`

=>

`{:startDateTime=>"2016-02-08T00:00Z", :timeZone=>{:text=>"(GMT) Monrovia, Reykjavik", :selected=>true, :offset=>"+00:00", :name=>"Greenwich Standard Time"}, :recurrencePattern=>"FREQ=MINUTELY;INTERVAL=1;UNTIL=20160211"} `

When I initiate scheduler with above Hash, it doesn't work:

`<script type="text/javascript">
  $('#myScheduler').scheduler('value', {:startDateTime=>"2016-02-08T00:00Z", :timeZone=>{:text=>"(GMT) Monrovia, Reykjavik", :selected=>true, :offset=>"+00:00", :name=>"Greenwich Standard Time"}, :recurrencePattern=>"FREQ=MINUTELY;INTERVAL=1;UNTIL=20160211"} );
</script>`

Preview: [http://imageshack.com/a/img922/4043/iFETl1.png](url)

**Comment by swilliamset** [comment]
The content passed to the scheduler needs to be JSON object. Converting to a Ruby Hash object for use in the initialization javascript will not work.
