### ISSUE TITLE
Scheduler Timezone JSON object doesn't handle right values

### ISSUE THREAD

**Issue by wlodi83** [ExactTarget/fuelux#1713]
Hi,

I initiate scheduler with following Javascript code:

`$('#myScheduler').scheduler('value', {"startDateTime":"2016-02-10T03:30Z","timeZone":{"text":"(GMT) Casablanca *","selected":true,"offset":"+00:00","name":"Morocco Standard Time"},"recurrencePattern":"FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=3;COUNT=2"});`

The problem is that Timezone text is "(GMT-06:00) Central Standard Time" instead of "Casablanca": 
![image](https://cloud.githubusercontent.com/assets/8006971/13179854/f475c44c-d6f3-11e5-9026-180075d27766.png)

**Comment by cormacmccarthy** [comment]
Try this instead:

```
$('#schedulerIllustration').scheduler('value', {"startDateTime":"2016-02-10T03:30Z","timeZone":{"offset":"+00:00"},"recurrencePattern":"FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=3;COUNT=2"});
```
