### ISSUE TITLE
Tree:clearSelection()

### ISSUE THREAD

**Issue by mkhahani** [ExactTarget/fuelux#1715]
I could not find in docs neither in issues. How can I clear the selected nodes of the Tree?

**Comment by mkhahani** [comment]
Any Idea?

**Comment by cormacmccarthy** [comment]
Just call selectItem on the item again.

So, if you select the item like this:

`$('#myTree').tree('selectItem', $('#item1'));`

Calling that exact same method again will function as a deselect. Admittedly not the greatest name for the method...

**Comment by mkhahani** [comment]
Thanks for the reply but for my need the `deselectAll` does the trick.
