### ISSUE TITLE
Bad sample code in documentation

### ISSUE THREAD

**Issue by TheJaredWilcurt** [ExactTarget/fuelux#1730]
There are several syntax errors in the sample code in the Repeater Options documentation, seen here:

* http://getfuelux.com/extensions.html#bundled-extensions-list-options

Source code here:

* https://github.com/ExactTarget/fuelux/blob/gh-pages/_includes/extensions/repeater-list.html#L217

**Comment by cormacmccarthy** [comment]
fixed.
