### ISSUE TITLE
Add ability to cancel repeater search

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1733]
Add ability for user to cancel an in-progress search on the repeater.

Possibly fire a "searchCancelled" event. Make sure that if the long-running search does eventually execute successfully there is a way to keep it from clobbering the repeater values/display.

Requested by Brian Tuttle for email team.

**Comment by swilliamset** [comment]
Confirm on cancel repeater returns to cached (previously displayed) records
