### ISSUE TITLE
How to customize culture of DatePicker?

### ISSUE THREAD

**Issue by juanonsoftware** [ExactTarget/fuelux#1734]
Is it possible to customize culture using css/html attributes? I see the javascript way but via attribute seems more convenience.
Thanks for your great work.

**Comment by jmgekeler** [comment]
We do not provide a way to set the DatePickers culture other than via javascript. 

`$('#myDatepicker').datepicker('setCulture', 'fr');`

You can see the complete DatePicker documentation here: http://fuelux.herokuapp.com/controls/date-picker
