### ISSUE TITLE
I can't seem to be able to trigger change on Selectlist

### ISSUE THREAD

**Issue by kdon80** [ExactTarget/fuelux#1735]
I'm trying to programmatically trigger change on select list, but JQUERY's .trigger('change') doesn't seem to have affect.

    $x.selectlist('selectBySelector', 'li[data-something='+data+']').trigger('change');

thanks,

**Comment by jmgekeler** [comment]
If I am understanding this correctly, you just want to set a selected value on the selectlist. You do not need to trigger a change event.

Leave off the `.trigger('change')`. So...

`$x.selectlist('selectBySelector', 'li[data-something='+data+']')`

You can see the complete selectlist documentation here: http://fuelux.herokuapp.com/controls/selectlist

**Comment by swilliamset** [comment]
you'll want to listen to the event thrown by the control as mentioned in the documentation linked above.

![image](https://cloud.githubusercontent.com/assets/347227/13335719/6b846048-dbe0-11e5-8e6e-19cdb983c2e9.png)
