### ISSUE TITLE
Bug on filling a repeater hidden

### ISSUE THREAD

**Issue by ferulisses** [ExactTarget/fuelux#1736]
I tried to fill a container with a repeater using a JSON result, but I was keeping the container hidden until loading all data.

I got a stranger error, the autoWidth and autoHeight of the title didn't work, leaving a stranger <div> in it.

I discovered that this line was receiving 0 instead of the correct size:
var outerWidth = $th.find( '.repeater-list-heading' ).outerWidth();

Here is a preview with a line with a stranger line plotted:

![image](https://cloud.githubusercontent.com/assets/3842252/13332359/5d72b0c2-dbe0-11e5-9c46-b5c3095fffb2.png)

I think that when the size returns 0, you can ignore it and don't set the width.

**Comment by jmgekeler** [comment]
Hi ferulisses. 

The repeater will not render the correct height and width if you instantiate it while hidden.  You can either instantiate it after the container is shown or you may try calling `resize` after the container is shown like so:

` $('#myRepeater').repeater('resize'); `

Let me know how that works for you.
