### ISSUE TITLE
Repeater Select/Deselect Behavior

### ISSUE THREAD

**Issue by mkhahani** [ExactTarget/fuelux#1742]
Respecting all the great features of Repeater, I am in trouble with the current row-select behavior. Consider I have a list of items and user can navigate through the list by clicking on each row to see the detail information of that item in a form.

The problem is that when user clicks on a row that has been selected before then it turns deselected while the form is still shown and there is no way to avoid or disable this behavior.

So I have to handle the `Repeater:deselected` event to hide the form. But now each time user clicks on a row, two events occur and the form flashes (turns hidden on deselecting old row and is shown again on selecting new row) which is not good. What I need, and is expected in most cases, is that when user clicks on a row despite it is selected or not, it should be kept selected. Deselecting can be handled by developer. For instance a cancel button which hides the form and clears the selected row.

This approach also is useful in multi select mode. When a row (not the checkbox) is clicked then it should select only clicked row clearing all the previous selected rows (single select behavior). User still can select multiple rows by using checkboxes.

Having also a separated event other than `Repeater:selected` for row clicks can also help in multi select mode just like Gmail which benefits from both click on a row and multi-selecting by checkboxes. By the current approach you can not create a Gmail like datagrid.

This also can be applied to Repeater:Tree #1724

**Comment by jmgekeler** [comment]
Hello mkhahani,

The Fuel UX Repeaters default behavior is to deselect a selected row when that row is clicked. 

However, you can write your own Repeater Extension to make the Repeater do whatever you would like. Documentation can be found here: http://getfuelux.com/extensions.html#writing-extensions

In your case, it sounds like you can use the existing Repeater List extension and with a few modifications, you can change the row selection behavior.

**Comment by mkhahani** [comment]
Hi jmgekeler,

Thanks for the advice. Actually I am using a workaround for the moment by adding some new events over row clicks and preventing the default Repeater events. The drawback of writing new extension or customizing an existing one is maintenance and keeping up to date with Repeater changes.
