### ISSUE TITLE
 Does anyone know how to get dynamic tree data from server?

### ISSUE THREAD

**Issue by AhaSleeper** [ExactTarget/fuelux#1775]
1.Here is my html code snippet:
`<div class="widget-body">
                                        <div class="widget-main padding-8">
                                            <ul id="tree1"></ul>
                                        </div>
                                    </div>`
2.get dynamic data from server:
`var DataSourceTree = function (options) {
        this.url = options.url;
    }

    DataSourceTree.prototype.data = function (options, callback) {
        var param = null

        if (!("name" in options) && !("type" in options)) {
            param = 0;//load the first level
        }
        else if ("type" in options && options.type == "folder") {
            if ("additionalParameters" in options && "children" in options.additionalParameters) {
                param = options.additionalParameters["id"];
            }
        }

        if (param != null) {
            $.ajax({
                url: this.url,
                data: 'id=' + param,
                type: 'POST',
                dataType: 'json',
                success: function (data) {
                        callback({ data:data })
                },
                error: function (response) {
                }
            })
        }
    };
    $('#tree1').ace_tree({
        dataSource: new DataSourceTree({url:"/menu/tree"}),
        multiSelect:false,
        loadingHTML:'<div class="tree-loading"></div>',
        'open-icon' : 'ace-icon tree-minus',
        'close-icon' : 'ace-icon tree-plus',
        'selectable' : true,
        'selected-icon' : 'ace-icon fa fa-check',
        'unselected-icon' : 'ace-icon fa fa-times'
    });`
however,it didn't work! and I get an error  "Uncaught TypeError: this.options.dataSource is not a function". if anyone knows how to fix it, please tell me.Thank you!

**Comment by futuremint** [comment]
`dataSource` is expected to be a function. I don't know what your constructor for DataSourceTree looks like because you didn't include it, but it likely is _not_ returning a function and returning an object or maybe the implicit `this`. Find out what `new DataSourceTree({url:"/menu/tree"})` returns and down that path lies your problem.
