### ISSUE TITLE
Repeater: pageChanged.fu.repeater fires itself twice on every pagechange

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux#1790]
Bind the pageChanged.fu.repeater to your repeater, in my example it is spitting out a console.log. See that the event is fired twice when the user changes the page number in the input box.

Expected Result: this event is fired once.

If this worked as expected it would facilitate a way to limit the user from entering page numbers out of the range provided by the datasource.

CodePen example: http://codepen.io/dkilgore/pen/oxpNzj

**Comment by interactivellama** [comment]
It looks like this is a combobox control issue. At some point in the recent past, it looks like the UX pattern for combobox changed to only allow options within the dropdown menu. This was after the repeater control was created. Therefore if you enter a number not on the dropdown list. It is changed on pressing enter and then again when combobox forces it back to an item in the list.

I've been able to duplicate this at http://localhost:8000/#combobox
If you type in something not on the list, it goes to another item on the list "Two2" becomes "Three". I'll have to dig into combobox to figure this out.

Thanks @dkilgore for bringing this to our attention.

**Comment by interactivellama** [comment]
@dkilgore Would you be able to pull this down and see if it solves your problem here. `pageChanged` should only be emmiting once now.

The dist is built so that should be able to be copy/pasted.

https://github.com/interactivellama/fuelux/tree/combobox-select-changed

**Comment by dkilgore** [comment]
@interactivellama Works for me, thanks for the fix! :shipit:
