### ISSUE TITLE
How could I make fule ux rtl 

### ISSUE THREAD

**Issue by monajafi** [ExactTarget/fuelux#1813]
Hi
I need the RTL version of fuel ux . How can I change the css and javascript files to support RTL
Is it easy to do this?

**Comment by vernak2539** [comment]
@monajafi check [this](https://code.byvernacchia.com/2015/06/19/fuelux-rtl-wizard/) out for the wizard RTL. Don't think it would be too much work for the rest of them, maybe just some styling changes.
