### ISSUE TITLE
Spinbox changes when scrolling page

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1814]
Scroll down a page with a spinbox. When you the cursor gets over the page it gets stuck and spins the spinbox instead of continue the scroll.

**remove scroll to change spinbox all together** (updated based on thread below)

![may-20-2016 10-19-04](https://cloud.githubusercontent.com/assets/347227/15430669/5af19d28-1e74-11e6-9fe2-c26e27ec4875.gif)

**Comment by mbeard** [comment]
We should mimic the standard `<input type="number" >` as much as possible.  I don't believe it supports this functionality.

**Comment by jamin-hall** [comment]
+1. To confirm I checked w3schools (
http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number). The
only way to increment/decrement is to click on the buttons or use the
up/down keys.

On Fri, May 20, 2016 at 10:35 AM, Matt Beard <notifications@github.com>
wrote:

> We should mimic the standard <input type="number" > as much as possible.
> I don't believe it supports this functionality.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ExactTarget/fuelux/issues/1814#issuecomment-220622879>
>



-- 

JAMIN HALL

Lead Interaction Designer | salesforce.com

Mobile: 317-701-4990

**Comment by interactivellama** [comment]
This looks like we have decided to remove by default and break the current "user experience". I do not have issue with breaking the "user experience" as long s the API isn't breaking in a bugfix release.

**Comment by swilliamset** [comment]
Lets remove the functionality all together
