### ISSUE TITLE
Repeater Column Header Markup Bug

### ISSUE THREAD

**Issue by scott-joe** [ExactTarget/fuelux#1829]
https://github.com/ExactTarget/fuelux/blob/master/js/repeater-list.js#L690

The input should be inside the label. It's causing issues in other theming efforts.

**Comment by scott-joe** [comment]
@jamin-hall update repeater example to remove custom styling once this is fixed.

**Comment by cormacmccarthy** [comment]
This appears to be fixed.

https://github.com/ExactTarget/fuelux/blob/master/js/repeater-list.js#L657
