### ISSUE TITLE
Wizard within an iframe causes problems on mobile devices

### ISSUE THREAD

**Issue by asteinbr** [ExactTarget/fuelux#1855]
I observed a problem with the FuelUX Wizard when using an iframe.

For a test I took your example wizard from the Controls-webpage and put it into a simple iframe-tag. On my desktop's Chrome browser the iframe works as desired, however on a iPad with Chrome or Safari the iframe with the wizard was presented wrongly.

iframe-code:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

    </style>
</head>
<body>
iframe
<iframe src="iframe_content.html"></iframe>

</body>
</html>
```

I uploaded an example to show you the problem: http://a19r.rasalhague.uberspace.de/iframe/iframe_test.html

Screenshot from the iPad:
![img_0031](https://cloud.githubusercontent.com/assets/1075297/17680759/2639d9d4-6342-11e6-9be5-cf1b14d663e7.PNG)

Is the way how I try to use the iframe wrong?

**Comment by futuremint** [comment]
Try setting the width of your iframe.  The wizard expands to fill its container, so in this case you need to set the width of your iframe to a more iPad friendly width (which is 1024 "virtual" pixels wide).  You may also have to set the width of the wizard inside the iframe too.
