### ISSUE TITLE
Stacked (Vertical) Tabs in Wizard

### ISSUE THREAD

**Issue by tacman** [ExactTarget/fuelux#1860]
Is it possible to have vertical tabs in the wizard, instead of across the top?  I like where the Next/Prev/Save buttons are, but vertical tabs should fit better with our user interface.

The stacked nav tabs here: http://getbootstrap.com/components/#nav-pills

So something like class="steps-stacked" or "steps steps-stacked"?

**Comment by cormacmccarthy** [comment]
No, this is not possible out of the box.

**Comment by kcivey** [comment]
It looks like this got added to the 3.15.8 milestone but never reopened, so the milestone closed without it ever being handled.

**Comment by tacman** [comment]
Is it possible to re-open this?
