### ISSUE TITLE
Paging is not working as it did previously for repeater with infinite scroll

### ISSUE THREAD

**Issue by aheile** [ExactTarget/fuelux#1867]
With the latest fuelux update, our repeater is no longer paging data correctly. After the first page, the pageIndex is ending up NaN.  After digging in further, it appears to be happening with this line:
https://github.com/ExactTarget/fuelux/blob/master/js/repeater.js#L254

renderItems() calls the callback() and so "d" is always undefined. If I remove "state.data = d;" then the paging works again.

```javascript
function callAfterRender (d) {
    state.data = d;
    afterRender.call(self, state);
}
```

![image](https://cloud.githubusercontent.com/assets/393424/18684612/cd33b78e-7f42-11e6-8453-fd5df74d2912.png)

@cormacmccarthy

**Comment by mtrepina** [comment]
FYI @swilliamset @interactivellama

**Comment by cormacmccarthy** [comment]
@aheile can you try modifying that `callback()` line to say `callback(data)` and see if that fixes please? We are looking into the issue now, and, believe that will be the fix we put in place, but, want to make sure it actually fixes it for you.

**Comment by aheile** [comment]
@cormacmccarthy @swilliamset Thank you, yes, that fixes it.

**Comment by cormacmccarthy** [comment]
@aheile I have a PR open. Once it is merged in, we will do a release as soon as we can. In the meantime, feel free to manually implement the fix.
