### ISSUE TITLE
[Bug] Wizard event "click.fu.wizard" should not fire when content includes li elements

### ISSUE THREAD

**Issue by aiperon** [ExactTarget/fuelux#1877]
I've noticed unexpected steps switching on Wizard widget. 

- Add the next code to the first .step-pane element:
```
<ul>
  <li class="complete">First item</li>
  <li class="complete">Second item</li>
</ul>
  ```
- Click on "First item" row

Expected result: nothing should happened.
Actual result: last step would be activated.

The reason is selector for steps elements ("li.completed") located inside all of the wizard element:
https://github.com/ExactTarget/fuelux/blob/master/js/wizard.js#L60

My suggestion:

    var stepsContainer = this.$element.children('steps-container')
    stepsContainer.on('click.fu.wizard', 'li.complete', $.proxy(this.stepclicked, this));

Could I provide PR for that?

**Comment by cormacmccarthy** [comment]
Yes, please do provide a PR!

Please provide unit tests for this as well.

**Comment by aiperon** [comment]
@cormacmccarthy Could you take a loot at the PR https://github.com/ExactTarget/fuelux/pull/1879 ?
