### ISSUE TITLE
Problem installing packages via yarn.

### ISSUE THREAD

**Issue by kguevara** [ExactTarget/fuelux#1881]
error fuelux@3.15.8: The engine "node" is incompatible with this module. Expected version "5.8.x".
error Found incompatible module

node -v: v6.5.0

**Comment by swilliamset** [comment]
Sorry we don't have plans to support yarn. If you would like to issue a PR we would be happy to review it.

**Comment by swilliamset** [comment]
@kguevara reassessed thanks for your contribution. we have reassessed our yarn support and realize there is no reason to not support it 🎉 . please let us know if you have any other issues.
