### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by robledosm** [ExactTarget/fuelux#1900]
Awesome work!

Any chance of adding TypeScript support? 

Regards

**Comment by futuremint** [comment]
Do you mean writing a type declarations file?

**Comment by robledosm** [comment]
Hi Dave,

Yes, the type declarations file. I'm working on creating it, but I'm new to TypeScript 

Regards,

**Comment by futuremint** [comment]
This is an open source project, so you're more than welcome to contribute.  I have some Typescript experience, so I can check your declarations file if you want and give you feedback.  Just send us a PR and assign it to me.  They have some great documentation on how to go about writing a declarations file: https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by robledosm** [comment]
Thanks Dave, 

What I have is still in draft, will keep you posted

Regards,

**Comment by cormacmccarthy** [comment]
Feel free to submit a PR when ready. Thanks for your interest.
