### ISSUE TITLE
Way to get Datasource from tree API

### ISSUE THREAD

**Issue by Hilgo** [ExactTarget/fuelux#1911]
I am using Fuelux Tree and included a sort option with [JQuery UI Sortable](https://jqueryui.com/sortable/), because i needed to get the selected items in order. I managed to implement this without many problems, figured a way to even include some rules in sorting, like the children items can't leave their parents to higher or lower hierarchical levels. The `selectedItems` get the items in the order that users sort them.

The only problem comes when I need to load the register from database, i can't load the tree in the same order that the user sorted it, i can show only the selected items in order, but i would like to show their respective folders as well.

I know that the Datasource works using callbacks and i took a look in the Fuelux Tree code to see if the Datasource would be sorted as well, it doesn't, that must be because the sort is only in the HTML tags, and the `selectedItems` returns sorted because it does a JQuery selector of the selected items, include them in a array and then returns it. 

In load my tree using ajax and json, i get my entire structure once and used an datasource function that came with a [template ](https://wrapbootstrap.com/theme/ace-responsive-admin-template-WB0B30DGR)that uses fuelux, that way i don't make any more requests when users expands folders, i do it only once.

Just to show better, here's what i am trying to do:

Imagine that this is my initial tree that i load in an alphabetical order and including it's children after all root items:
![initial](https://cloud.githubusercontent.com/assets/7366331/21180898/47503088-c1e2-11e6-8135-e49716b5ae7a.png)

And this would be a sorted tree, after user changed places to its needs:
![sorted](https://cloud.githubusercontent.com/assets/7366331/21180897/474d1a4c-c1e2-11e6-9470-dd7035ce025e.png)

What i am trying to do is comparing my default initial list and trying to sort accordingly to the `selectedItems`, but i am not being able to do this, its too complex for me but i believe its still possible. But if i could get the datasource sorted, i could save that and load without any problems.

Anyway, this is a great plugin, but maybe i should use another to suit my need to load a register. I don't want to, because i use it in other parts of the application. I Hope that i described my situation clear enough, and sorry for any grammar and orthography mistakes or if this is not the place to post this kind of question.

**Comment by cormacmccarthy** [comment]
That datasource is not actually part of Fuel UX. You entirely provide and control the datasource. I can't see your datasource code, but the tree just displays whatever you tell it to display through your datasource. Trying to sort the stuff that the tree spits out to the page using some sort of jQuery plugin is not the way you'd want to go. Use underscore or lodash or something to sort the stuff right in the datasource before sending it back to the tree for display.
