### ISSUE TITLE
Possible to hide or disable a step(tab) in wizard?

### ISSUE THREAD

**Issue by tacman** [ExactTarget/fuelux#1923]
Is it possible to hide or disable a tab in the wizard?

For example, if the first tab has a checkbox "Under 18", then when checked, we want activate another tab for parent/guardian permission and contact.  If they uncheck it, we'd hide or disable that tab.  (Not our actual use case, but that idea).

We can use .addStep and .removeStep, but was hoping there might be a way to simply disable a tab, like Bootstrap does with the .disabled class.  

http://getbootstrap.com/components/#nav-disabled-links

Obviously, it's more complicated in the FuelUx wizard, because the "next" button then needs to skip that tab, etc.

**Comment by swilliamset** [comment]
No that functionality is not built into the wizard. Also manipulating the wizard based on interactions within the wizards is contrary to our design guidance. The steps in the wizard should not change once the wizard has begun. I would recommend moving the attribute you are checking for outside the wizard. That way you have the information before rendering the wizard.
