### ISSUE TITLE
Repeater sets height to 0 when resized inside of display:none div

### ISSUE THREAD

**Issue by austin-rauschuber** [ExactTarget/fuelux#1944]
Whenever the repeater is placed inside of another DOM element whose display is set to none, the resize function of the repeater results in the height being set to 0. This ultimately leads to the following issue occurring frequently:

-  Load tab/modal that includes the repeater
-  Close tab/modal
-  Resize screen
-  Reopen tab/modal
Expected Result: Repeater height is resized properly to size of window
Actual Result: Repeater height is set to 0

While you can simply trigger a resize event whenever you open the tab/modal again, this seems unreasonable and "hackish" to include in every location in which the repeater is used.

My suggested solution is to adjust all parents of the repeater that are hidden to be set to "display:block" for the duration of the resize function and then reset to their prior values afterwards. Due to the single-threaded nature of javascript, I believe that the UI thread won't ever be picked up during the execution of the function causing the changes to not affect the browser's rendering of the page.

**Comment by swilliamset** [comment]
closed by #1946
