### ISSUE TITLE
Datepicker uses require() in a way that is not compatible with webpack < v2.0.

### ISSUE THREAD

**Issue by RodEsp** [ExactTarget/fuelux#1985]
[Line 52 of datepicker.js](https://github.com/ExactTarget/fuelux/blob/master/js/datepicker.js#L52) passes in an function as a third argument to require(). This seems to be incompatible with Webpack's implementation of require().

![image](https://cloud.githubusercontent.com/assets/1084688/26691596/b8e4b066-46cb-11e7-916b-9cd6851b63de.png)

I am seeing this when trying to run unit tests via Karma. As soon as I delete that third argument to require() the warning goes away and PhantomJS does not error out anymore.

**Comment by vernak2539** [comment]
until they fix the umd wrappers so it can be imported as a cjs module correctly (and provide it's own package to do so), this is what we had to do

**Webpack config**
```
function resolvePath(file) {
	return path.resolve(__dirname) + file;
}

...
resolve: {
	modules: [path.join(__dirname, './src'), 'node_modules'],
	alias: {
		'fuelux/checkbox': resolvePath('/node_modules/fuelux/js/checkbox'),
		'fuelux/combobox': resolvePath('/node_modules/fuelux/js/combobox'),
		'fuelux/datepicker': resolvePath('/node_modules/fuelux/js/datepicker'),
		'fuelux/dropdown-autoflip': resolvePath('/node_modules/fuelux/js/dropdown-autoflip'),
		'fuelux/infinite-scroll': resolvePath('/node_modules/fuelux/js/infinite-scroll'),
		'fuelux/loader': resolvePath('/node_modules/fuelux/js/loader'),
		'fuelux/radio': resolvePath('/node_modules/fuelux/js/radio'),
		'fuelux/repeater': resolvePath('/node_modules/fuelux/js/repeater'),
		'fuelux/search': resolvePath('/node_modules/fuelux/js/search'),
		'fuelux/selectlist': resolvePath('/node_modules/fuelux/js/selectlist'),
		'fuelux/spinbox': resolvePath('/node_modules/fuelux/js/spinbox'),
		'fuelux/utilities': resolvePath('/node_modules/fuelux/js/utilities'),
	}
},
```

**inclusion in app**
```
require('bootstrap');

require('fuelux/js/checkbox');
require('fuelux/js/combobox');
require('fuelux/js/datepicker');
require('fuelux/js/infinite-scroll');
require('fuelux/js/loader');
require('fuelux/js/pillbox');
require('fuelux/js/placard');
require('fuelux/js/radio');
require('fuelux/js/repeater-list');
require('fuelux/js/repeater-thumbnail');
require('fuelux/js/repeater');
require('fuelux/js/selectlist');
require('fuelux/js/spinbox');
require('fuelux/js/search');
require('fuelux/js/spinbox');
require('fuelux/js/picker');
require('fuelux/js/scheduler');
require('fuelux/js/tree');
require('fuelux/js/wizard');
require('fuelux/js/dropdown-autoflip');
```

**Comment by swilliamset** [comment]
@vernak2539 do you have more info on 
> until they fix the umd wrappers so it can be imported as a cjs module correctly

**Comment by RodEsp** [comment]
It appears that this particular issue has been accounted for in Webpack 2.0.
https://github.com/webpack/webpack/pull/3247/files

**Comment by vernak2539** [comment]
@swilliamset will do tomorrow

**Comment by vernak2539** [comment]
Looking at it now, I believe it was the way we were including it. I ended up trying about every way under the sun when first transitioning from requirejs to webpack. I'll report back and see if I can get it to work differently with the exiting files

**Comment by vernak2539** [comment]
@RodEsp we are in the process of fixing this. The long and short of it is: Since webpack understands almost all module types, when it tries to include fuelux, it actually uses the AMD define, instead of the module.exports, and uses that. If you don't have the correct alias' set up, it will fail to find modules.

We are either going to to define a webpack test that excludes the define statement or we will be re-ordering all the UMD wrappers.

**Comment by vernak2539** [comment]
Also, this would require you to not use the `fuelux.min.js`file. @swilliamset maybe we can include the npm dist file back into the repo?

**Comment by vernak2539** [comment]
I'll submit a update to the readme or something about using with webpack, but here's the guts to fix this.

```
npm install --save-dev imports-loader
// or 
yarn add --dev imports-loader
```

webpack 2 config

```js
// add as a rule under module.rule
{
	test: /fuelux\/js\/.*\.js$/,
	use: ['imports-loader?define=>false']
}
```

lib/fuelux.js
```js
'use strict';

require('bootstrap');

require('fuelux/js/checkbox');
require('fuelux/js/combobox');
require('fuelux/js/datepicker');
require('fuelux/js/infinite-scroll');
require('fuelux/js/loader');
require('fuelux/js/pillbox');
require('fuelux/js/placard');
require('fuelux/js/radio');
require('fuelux/js/repeater-list');
require('fuelux/js/repeater-thumbnail');
require('fuelux/js/repeater');
require('fuelux/js/selectlist');
require('fuelux/js/spinbox');
require('fuelux/js/search');
require('fuelux/js/spinbox');
require('fuelux/js/picker');
require('fuelux/js/scheduler');
require('fuelux/js/tree');
require('fuelux/js/wizard');
require('fuelux/js/dropdown-autoflip');
```

where you want to include it
```js
require('lib/fuelux')
```

**Comment by vernak2539** [comment]
PRs for this are here https://github.com/ExactTarget/fuelux/pull/1988

**Comment by cormacmccarthy** [comment]
Looks like this is resolved? If not fee free to re-open. Thanks!

**Comment by RodEsp** [comment]
I don't know if I would call this resolved because it still requires the user of FuelUX to change their application in order to make it work with FuelUX. I would say FuelUX should just work natively out of the box with Webpack 1.0 for this to be resolved.
But that's just my 2 cents.

**Comment by cormacmccarthy** [comment]
OK. If it is important to someone enough for them to want to fix it, that person is free to re-open and issue a PR. Thanks!

**Comment by vernak2539** [comment]
I think this is the best we're going to get without modifying the UMD wrapper in all files
