### ISSUE TITLE
When user clicks row redirect to new page.(Repeater)

### ISSUE THREAD

**Issue by Ryanb58** [ExactTarget/fuelux#2003]
Build a simple repeater with `list_selectable: single`. Now i can select a single row. However, I want to perform an action upon a user clicking on the row, such as redirecting to a link. How do I accomplish this?

Actual results, the item is just highlighted.

**Comment by futuremint** [comment]
Listen for `selected.fu.repeaterList` event. http://getfuelux.com/extensions.html#bundled-extensions-list-events
