### ISSUE TITLE
webpack import fuelux

### ISSUE THREAD

**Issue by LiuXiao617111** [ExactTarget/fuelux#2010]
when i import fuelux ,then use webpack to pact it,  it throw 

> Module not found: Error: Can't resolve 'data' in 'xxx\node_modules\fuelux' . 

l try to find the  problem . In the fuelux/package.json , l find "main" property value is "./dist/js/npm",but there is no file can be find.  then i change the value to "./dist/js/fuelux.js" , it's to be fine.

**Comment by vernak2539** [comment]
Please see this section http://getfuelux.com/getting-started.html#templates

**Comment by LiuXiao617111** [comment]
thank you , when l add reslove/alias and  module/rules in webpack.config.js  . it's Just fine
`resolve: {
        alias: {
            fuelux: path.join(__dirname, "/node_modules/fuelux/dist/js/fuelux.js")
        }
    },`

`{
                test: /fuelux\/js\/.*\.js$/,
                use: ['imports-loader?define=>false']
            },`
