### ISSUE TITLE
Dependency on eslint-plugin-react 

### ISSUE THREAD

**Issue by rob4acre** [ExactTarget/fuelux#2035]
Is the dependency on eslint-plugin-react really required in production?

Just wondering if this could this be moved to a devDependency? In my case, it causes unwanted packages to be installed in a production deployment.

**Comment by vernak2539** [comment]
It looks like these two need to be moved to devDeps. Can take a look tomorrow and hopefully change it.

```

"babel-eslint": "^7.2.3",
"eslint-plugin-react": "^7.0.1",
```

**Comment by vernak2539** [comment]
This will be released in `3.16.6`, but I'm needing permissions, which were removed, to publish it

**Comment by rob4acre** [comment]
thanks!

**Comment by vernak2539** [comment]
should be published now

**Comment by rob4acre** [comment]
I just upgraded and this removed about 50 unrequired packages from my node_modules directory. Thanks!
