### ISSUE TITLE
How to complete CRUD feature in datagrid?

### ISSUE THREAD

**Issue by xautjzd** [ExactTarget/fuelux#344]
Lately,I want to implement the CRUD feature using fuelux Datagrid components,but can't find a proper sample or code snips,I want to impletement the effect: `when press "Add", it pop a dialog to input item; 
when select one row and press "Edit", pop a dialog filled with the selected rows item`. Can fuelux provide the fuction? I have read the document about datagrid,but can't find it

**Comment by swilliamset** [comment]
@ripleyXLR8 consider solving repeater. if you can provide a snippet  we would love to share it with the community. our repeater view extension framework should allow for this. otherwise this is great for future roadmap considerations.
