### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux#741]
Need a color picker control to enable selecting basic and advanced colors.  Should have methods for setting and retrieving selected color.  Also need to ensure we can support different variants for generically picking a color vs. picking a foreground or background color.

![screenshot 2014-10-16 13 37 14](https://cloud.githubusercontent.com/assets/467352/4667267/2163d56e-555b-11e4-8fdb-75bcbb9823e0.png)

Variants:
Palette
![screenshot 2014-10-16 13 39 01](https://cloud.githubusercontent.com/assets/467352/4667303/7b3dffa6-555b-11e4-811b-5f6c53ded408.png)

Foreground Color
![screenshot 2014-10-16 13 39 10](https://cloud.githubusercontent.com/assets/467352/4667310/827f7448-555b-11e4-801b-154b0a397e69.png)

Background Color
![screenshot 2014-10-16 13 39 23](https://cloud.githubusercontent.com/assets/467352/4667316/92e81e8e-555b-11e4-87db-6fc106b49442.png)

**Comment by kevinparkerson** [comment]
something like this would be great: http://colpick.com/plugin

**Comment by swilliamset** [comment]
For your consideration...

## Native HTML5 (per OS):

### OSX
<img width="548" alt="screen shot 2015-07-24 at 1 56 26 pm" src="https://cloud.githubusercontent.com/assets/347227/8881292/af46be76-320c-11e5-9001-dd34f2718d9c.png">

### Windows
<img width="675" alt="screen shot 2015-07-24 at 1 45 32 pm copy" src="https://cloud.githubusercontent.com/assets/347227/8881307/cca29cf6-320c-11e5-8fbf-1eec44adc8c0.png">

## jQuery Plugins:
http://colpick.com/plugin
<img width="380" alt="screen shot 2015-07-24 at 1 59 15 pm" src="https://cloud.githubusercontent.com/assets/347227/8881323/e2e06b2e-320c-11e5-8ff4-4beeaaa0bcb1.png">

## ET Element:
https://github.exacttarget.com/ETElements/colorpicker
<img width="587" alt="screen shot 2015-07-24 at 2 05 40 pm" src="https://cloud.githubusercontent.com/assets/347227/8881355/291ee58e-320d-11e5-89fc-e6ebeda9e1ed.png">

**Comment by swilliamset** [comment]
@jamin-hall we need to discuss this further

**Comment by kevinparkerson** [comment]
I vote a design like http://colpick.com/plugin! Simple, yet has the typical tools you need :+1:

**Comment by cormacmccarthy** [comment]
This is a candidate for an extension to picker. In fact, this could possibly be closed in favor of just creating a fuel ux snippet implementation of the picker.

**Comment by futuremint** [comment]
This can also be addressed in our yet-to-be-released internal framework very quickly with its better code sharing and modularity.

**Comment by futuremint** [comment]
We are not longer adding any new controls to this library.
