### ISSUE TITLE
Add additional tips for upgrading from Bootstrap 2 and Fuel UX 2

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#752]
http://getfuelux.com/migration.html

Review [page 19 and 20 of Fuel UX presentation](http://www.slideshare.net/interactivellama/cnx14-fuelux) for suggestions.

**Comment by Alondite00** [comment]
@interactivellama bottom tips?

**Comment by interactivellama** [comment]
@Alondite00 I'm not following. The last 5 or 6 slides have upgrading suggestions. Please add these to the migration documentation.
