### ISSUE TITLE
Repeater - too much recursion

### ISSUE THREAD

**Issue by meskobalazs** [ExactTarget/fuelux#774]
Currently the Repeater widget is simply broken in Firefox. Even on the official example site (http://getfuelux.com/javascript.html#repeater) the Repeater stops working, when I set the number of rows to 50 or more. The error that the browser reports is "too much recursion", and it dies after a few hundred cell drawing. We've tried to use it for a very large table (30+ columns), in that case it can't render 10 rows in Firefox.

**Comment by odan** [comment]
I've got the same issue with v3.5.1 in Firefox and Chrome.

Firefox 34 (36 rows, 9 columns): too much recursion
in: fuelux.js (file row 5433, file column 17)
> var $table = this.$element.find( '.repeater-list table' );)

Chrome v39: (315 rows, 9 columns): 
Uncaught RangeError: Maximum call stack size exceeded in jquery.js:346 (v1.11.1)

> camelCase: function( string ) {
>     return string.replace( rmsPrefix, "ms-" ).replace( rdashAlpha, fcamelCase );
> },

IE 11: error 80020101 in jquery.js:5732

**Comment by cristalembalagens** [comment]
I've commented in this post https://github.com/ExactTarget/fuelux/issues/534 that i'm getting the same issue.

**Comment by cormacmccarthy** [comment]
@cristalembalagens can you provide a jsfiddle or jsbin or something to help us look into this? We are having trouble reproducing. Thank you!

**Comment by cristalembalagens** [comment]
Just open and check your console. Used your own example data.

http://jsfiddle.net/4vz6rxsw/

**Comment by cormacmccarthy** [comment]
Thanks! I'm definitely seeing that now. I'll look into this.
