### ISSUE TITLE
Constrain combobox input to options

### ISSUE THREAD

**Issue by jabbett** [ExactTarget/fuelux#83]
Sometimes it's desirable to constrain combobox input to only the options available, i.e. let the user type a few letters to narrow the options from the list, but clear the value if the user exits the field without selecting a match.

I would recommend making this an option on combobox(), e.g.

```javascript
$(".selector").combobox({
    constrain: true
});
```

**Comment by swilliamset** [comment]
type ahead has been discussed as useful pattern. this is not in the scope for fuel 3 but will be  considered for a future major release.

cc @mbeard
