### ISSUE TITLE
Multi-Select component

### ISSUE THREAD

**Issue by aadrian** [ExactTarget/fuelux#84]
It would be nice if fuelux would have a **multi-select component** too. 

Pillbox is nice (but more for tags), but often something like an improved multi-select is required in forms. 

One possible candidate based on jQuery might be:
https://github.com/dio-el-claire/jquery-multiselect
with the live example: http://www.std42.ru/jquery-multiselect/

Thanks in advance.

**Comment by interactivellama** [comment]
This looks like a grouping of an <input> with a checkbox group.
