### ISSUE TITLE
Tree misbehaving in several ways.

### ISSUE THREAD

**Issue by mk23** [ExactTarget/fuelux#854]
I have an example with some contrived data here:  http://jsfiddle.net/kvbqnc29/5/

1. On _Safari 8.0_, selecting a leaf node changes the icons of the parents.  To reproduce the problem, open `Top Level Tree 2` and select either of the Leaf children.
1. On _Safari 8.0_, opening a folder fires the `selected.fu.tree` event.
1. On _FireFox 33.1.1_, opening folders doesn't work at all.

I am expecting that this is user error, and would love a pointer to support this theory.

**Comment by mbeard** [comment]
Was anyone able to reproduce this?  I was not able to.

**Comment by swilliamset** [comment]
also not able

**Comment by swilliamset** [comment]
jsfiddle http://jsfiddle.net/kvbqnc29/5/ not working in firefox 35.0.1 but successful in safari 8.0.3

folder doesn't open in firefox

**Comment by cormacmccarthy** [comment]
I seem to remember tree having had issues in jsfiddle in the past, so, here is a jsbin version of the same thing to rule out this being a jsfiddle issue: http://jsbin.com/neledeyanu/1/

**Comment by swilliamset** [comment]
@cormacmccarthy to provide more info on monday

**Comment by interactivellama** [comment]
@mk23 I think this is duplicate of the #1283 and should not be fixed. Selecting an item was causing folder icons to be changed due to the $.find() cascade.
