### ISSUE TITLE
Remove saucelabs from default Travis CI task

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#880]
SauceLabs does not run dependably. Proposal is to run tests in phantomJS only on TravisCI. Update wiki to add SauceLabs tasks before each release locally. 

We believe it's an edge case that JS would fail in one browser and not another (at this time), especially with all the jQuery going on in this repo. Saucelabs will still be tested before release

**Comment by cormacmccarthy** [comment]
I'm pretty sure this is done.

**Comment by cormacmccarthy** [comment]
```javascript
	// Travis CI task. This task no longer uses SauceLabs. Please run 'grunt saucelabs' manually.
	grunt.registerTask('travisci', 'Tests to run when in Travis CI environment', ['connect:testServer', 'jshint', 'qunit:full']);
```
