### ISSUE TITLE
IE9 datepicker has visual issues with how table is rendered

### ISSUE THREAD

**Issue by feitla** [ExactTarget/fuelux#889]
Columns are rendering incorrectly. Days of the weeks is overflowing and incorrectly calculating widths. Dates section is not spanning full width.

Win 7 IE9 

![screen shot 2014-11-26 at 3 25 30 pm](https://cloud.githubusercontent.com/assets/2625677/5210424/090d1e8a-7581-11e4-884c-aea675a88502.png)

**Comment by swilliamset** [comment]
@feitla PR's with working examples are always appreciated. Thanks for the info.
