### ISSUE TITLE
Pillbox edited event is not preserving existing value attribute for tag

### ISSUE THREAD

**Issue by tonyzampogna** [ExactTarget/fuelux#946]
When editing an existing tag with a value attribute (data-value='something'), that value is not sent along in the arguments when the edited.fu.pillbox is triggered.

**Comment by interactivellama** [comment]
I'm going to need some more information. I am getting `{value: "test", text: "test"}` from `edited.fu.pillbox`.

**Comment by swilliamset** [comment]
Problem is the markup isn't getting updated as explained here https://github.com/ExactTarget/fuelux/issues/960
