### ISSUE TITLE
Allow for inclusion via CommonJS (browserify)

### ISSUE THREAD

**Issue by vernak2539** [ExactTarget/fuelux#950]
Would probably have to update all templates to use something like https://github.com/umdjs/umd/blob/master/commonjsStrict.js. If it's worth it, would be willing to make the changes.

**Comment by juriejan** [comment]
+1

**Comment by interactivellama** [comment]
Anyone who works on this should review how Bootstrap did this: 
https://github.com/twbs/bootstrap/blob/master/Gruntfile.js#L479

**Comment by interactivellama** [comment]
Will be delayed until #1168 works itself out.

**Comment by dlandis** [comment]
Note: [there are issues using this with webpack](https://github.com/ExactTarget/fuelux/issues/1498).
