### ISSUE TITLE
tree selected event is triggered repeatedly

### ISSUE THREAD

**Issue by semudu** [ExactTarget/fuelux#953]
selected event is triggered for all sub tree items when clicked the parent node. i think it must be triggered one time for all items.

**Comment by cormacmccarthy** [comment]
I am also unable to replicate. Can you provide more info please? Here is a jsfiddle with a tree which has a selected listener properly applied:

http://jsfiddle.net/cmcculloh/n3deqemt/

Thanks!

**Comment by swilliamset** [comment]
Unable to replicate.
