### ISSUE TITLE
Bower error

### ISSUE THREAD

**Issue by SplicePHP** [ExactTarget/fuelux#964]
If I try to download the package via bower I get the following errror:
Fatal error: Unable to find suitable version for moment

Are you aware of this issue or is it specific to my configuration?

**Comment by vernak2539** [comment]
What version of Fuel UX are you trying to download? Also, what version of Moment.js is trying to be downloaded?

**Comment by SplicePHP** [comment]
I found the problem.
There was another package that had a conflicting dependency of moment:
"bootstrap-daterangepicker": "*"
I will fork a copy of that repo and change it's dependency from "moment": "~2.8.0" to "moment": "~2"
