### ISSUE TITLE
Tree: All items button API

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#969]
Seems like this top level/no-filter button should be a part of the tree control and not an external button that needs to be styled and events added to.

![screen shot 2015-01-08 at 11 37 04 pm](https://cloud.githubusercontent.com/assets/1290832/5675560/48127564-978f-11e4-8bcf-2fbd4612a8c3.png)

I'm thinking something that accepts HTML and returns an empty value for selected.fu.tree by default, or a data-value` if present.

```
treeOptions: {
  topLevel: '<button type="button" class="btn-link hidden-link all">All Items</button>' // 
}
```

**Comment by cormacmccarthy** [comment]
Can you elaborate a little further? What is "All Items" purpose and intent of "All Items" button? Does it "select all items" in the tree? Would all disclosable folders disclose?

**Comment by mbeard** [comment]
All items is a way to remove any filter criteria based on folder.  All items would be the default criteria and would ensure that your results encompassed all folders.

Essentially, it's the equivalent of adding an "All Items" root node to the tree.  You could accomplish the same thing by "deselecting" a selected node - by that may be less intuitive.  We need to work with @jamin-hall to verify the expected interaction here.
