### ISSUE TITLE
Don't override bootstrap background colours to allow bootstrap themes to work with fuelux

### ISSUE THREAD

**Issue by TMiguelT** [ExactTarget/fuelux#972]
I've been developing an app using the [superhero bootswatch theme ](http://bootswatch.com/superhero/), which is a dark theme that uses light text (unlike the default bootstrap theme). The problem is that some of the fuelux widgets (primarily *repeater* and *wizard*) have hard coded white backgrounds, which means they look terrible when combined with a dark theme, and worst of all the text is illegible.

 I added superhero to your [demo page](http://getfuelux.com/javascript.html) as a demonstration. You can do the same to see what I mean:
```javascript
var l = document.createElement("link");
l.rel = "stylesheet";
l.href = "//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/superhero/bootstrap.min.css";
b = document.querySelector("body");
b.appendChild(l);
```
Examples:
![capture](https://cloud.githubusercontent.com/assets/5019367/5691649/b905828c-9926-11e4-98df-85ba6b1f627e.PNG)
![capture](https://cloud.githubusercontent.com/assets/5019367/5691651/cb4ea018-9926-11e4-9251-2ad0a3dcb30d.PNG)

Would it be possible to use standard bootstrap classes like `.panel` and `.container` to make fuelux work better alongside bootstrap themes? Thanks so much for the library!

**Comment by interactivellama** [comment]
Thanks @TMiguelT. This is something to consider. We've had to theme these controls manually ourselves, too. See [Themed Fuel UX Controls](http://getfuelux.com/mctheme/index.html#mctheme) at the bottom. [These are the overrides](https://github.com/ExactTarget/fuelux-mctheme/tree/master/less/fuelux-override), we've had to write ourselves.

**Comment by interactivellama** [comment]
@TMiguelT How do other Bootstrap extensions (JS plugins) handle this? Are you using any that are as complex that handle this well?

**Comment by TMiguelT** [comment]
Well all bootstrap plugins I've used use bootstrap classes so I've never noticed this problem before. I did a little playing around, and I think with very little effort the wizard could be fixed to work with custom themes.

In the below examples I only changed 3 things with the wizard CSS:
* Added the `.panel` class to the `.wizard` element
* Removed the `background-color` from `.fuelux .wizard`
* Removed the `background-color` from `.fuelux .wizard > .actions` (the top right panel with the buttons)

If you compare them to the examples I posted at the top, I think they're a lot better. They're certainly legible now.

Superhero (dark) theme:
![panel dark](https://cloud.githubusercontent.com/assets/5019367/5714663/56016a60-9b20-11e4-9423-113092667266.PNG)
Default fuelux theme:
![white](https://cloud.githubusercontent.com/assets/5019367/5714665/591b76e6-9b20-11e4-8744-d782f806aef2.PNG)

**Comment by tjagusz** [comment]
@interactivellama definitively :+1:  on this. It would be nice if FuelUX would use standard bootstrap classes. This way theming would be easier.

**Comment by swilliamset** [comment]
can we do 
```
.wizard {
  &:not(.panel) {
    background-color: 
  }
}
```
around https://github.com/ExactTarget/fuelux/blob/master/less/wizard.less#L8

@Misiu or @TMiguelT if you would like to provide a PR and example we welcome the assistance
