### ISSUE TITLE
Document repeater dataSourceOptions and preserveDataSourceOptions

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#973]
`dataSourceOptions` - passes object of arbitrary key/value pairs to datasource (and we need to tell developers that in the datasource is where you want to sort, filter, search, etc.)
`preserveDataSourceOptions` - saves options in case you navigate to the next page, etc.

**Comment by Alondite00** [comment]
> dataSourceOptions - passes object of arbitrary key/value pairs to datasource (and we need to tell developers that in the datasource is where you want to sort, filter, search, etc.)
preserveDataSourceOptions - saves options in case you navigate to the next page, etc.

@interactivellama is this exactly what we want to put in the documentation?  And where?

**Comment by interactivellama** [comment]
It goes here: http://getfuelux.com/javascript.html#repeater-usage-options

Thanks, for picking this up. It fell into the cracks.

**Comment by interactivellama** [comment]
It also needs to noted here, too. Probably just mentioned and linked to http://getfuelux.com/javascript.html#repeater-dataSource

**Comment by interactivellama** [comment]
@Alondite00 Assign PR to @kevinparkerson

**Comment by kevinparkerson** [comment]
@Alondite00 make me the PR reviewer once you submit it please :)

**Comment by interactivellama** [comment]
@swilliamset @kevinparkerson I don't think @Alondite00 can be assigned this now that he's a full time designer.
