### ISSUE TITLE
Combobox doesn't fire input event when an item is selected

### ISSUE THREAD

**Issue by TMiguelT** [ExactTarget/fuelux#974]
Here's a [fiddle](http://jsfiddle.net/at56v8uv/). Basically the DOM event `input` ([see MDN](https://developer.mozilla.org/en-US/docs/Web/Events/input)) isn't fired on the `<input>` element when an option is picked from the combo box. This breaks some MV* frameworks that use the `input` event to trigger a scope update, for example [VueJS](http://vuejs.org/guide/forms.html#Lazy_Updates).

**Comment by mbeard** [comment]
@TMiguelT can you listen for the `change` event.  Here's a working [example](http://jsbin.com/necokamulo) of what I think you're trying to do?  The event is triggered in both cases where the user input text manually or choses an item from the menu.
