### ISSUE TITLE
Rails Assset precompilation fails!

### ISSUE THREAD

**Issue by zeitnot** [ExactTarget/fuelux#984]
[This][1] breaks sass compilations proccess with rails asset pipeline. It throws that:
`Sass::SyntaxError: @charset may only be used at the root of a document.`

[1]: https://github.com/ExactTarget/fuelux/blob/master/dist/css/fuelux.css#L8

**Comment by bglbruno** [comment]
I have the same problem

**Comment by cormacmccarthy** [comment]
It looks like we may be declaring @charset incorrectly. Looking into it.
