### ISSUE TITLE
Toggle checkbox and radio in docs are broken

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#985]
Remove `display:none` from checkbox markup (examples and markup).
See http://getfuelux.com/javascript.html#checkbox-examples-element-toggling

On a related note: The second toggle radio button is not clickable.
http://getfuelux.com/javascript.html#radio-examples-element-toggling

**Comment by mbeard** [comment]
The second radio lacks the containing div element with the `radio` class.
