### ISSUE TITLE
Repeater view documentation is unclear

### ISSUE THREAD

**Issue by scott-joe** [ExactTarget/fuelux#988]
I realize the Repeater can have multiple views, but I don't think the current documentation is clear enough about the options you have at your disposal and whether or not certain (relatively) key features, such as having selectable list items, have been abstracted out into a separate files.

**Comment by futuremint** [comment]
The list plugin is the default plugin.  Should we copy the docs for the list plugin from the extensions page into the main page of docs too?  I also ran into this issue before realizing that the _repeater_ is really just the container, and the _things inside_ are from whatever plugin you're using...
