### ISSUE TITLE
Scheduler reoccurance pattern loses weekday

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#992]
Bug found here: http://stackoverflow.com/questions/27974320/fuelux-scheduler-loose-the-information-of-day-when-we-select-weekly-recurrence

Change [L510](https://github.com/ExactTarget/fuelux/blob/master/js/scheduler.js#L510) to something like the following to include `attr('checked', true)`: `item.find( 'input[data-value="' + temp[ i ] + '"]' ).attr('checked', true).parent().addClass( 'active' );`

Add additional unit tests to test multiple reoccurrence patterns.

**Comment by mbeard** [comment]
To clarify, there are unit tests.  However, currently these check the DOM moreso to ensure that elements have the proper classes, checked attributes, etc.

We need additional tests to ensure that the value passed into schedule is what is returned.  Something like this:
```
var schedule = {
    startDateTime: '2014-03-31T03:23+02:00',
    timeZone: {
        offset: '+02:00'
    },
    recurrencePattern: 'FREQ=WEEKLY;BYDAY=WE;INTERVAL=6;BYSETPOS=3;UNTIL=20140919;'
};

$scheduler.scheduler('value', schedule);
equal($scheduler.scheduler('value'), schedule, 'schedule set correctly');
```
