### ISSUE TITLE
Re-invision and simplify checkbox and radio control

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#998]
This project has had issues with the custom checkbox control on and off for the last 3 releases. Is it time to deprecate the control?

Proposal:
- Should be "CSS-only" solution and fallback to native controls in <= IE8. (IE8 does not understand `:not` nor `:checked`. Let's use this to our advantage!)
- Should create an optional checkbox JS control that maintains compatibility (no breaking changes) with current control (is this possible?). However, it should just deal with the native checkbox as an API wrapper.

This was originally considered with the release of Fuel UX 3.0, but was shelved due to non-IE8 compatibility.

Any thoughts?

Links of interest:
http://www.wufoo.com/guides/custom-radio-buttons-and-checkboxes/
http://codepen.io/CreativeJuiz/pen/BiHzp

**Comment by cormacmccarthy** [comment]
Yeah, I think the checkbox should be ripped entirely out of Fuel UX. If we want, we could take the code an put it into a library just called "checkbox.js" or something (no association with Fuel UX) and tell people "if you want it, go and get it".

If we _really need to_ we could implement some sort of CSS only solution, but, I say we just say "a checkbox is a checkbox. Why make it look different?". We don't dictate that we want the browser chrome and scroll-bars to look different; this isn't IE6.

**Comment by futuremint** [comment]
#1019
